#include "NeuralRendering/Stage.h"
#include "NeuralRendering/PerformanceMetrics.h"
#include "nr-runtime/GpuProbeGuard.h"
#include <nvsdk_ngx_params.h>
#include <dxgi1_6.h>
#include <DirectXPackedVector.h>
#include <array>
#include <vector>
#include <cstdio>
using namespace TheosRenderPipeline::NeuralRendering;
using Microsoft::WRL::ComPtr;
namespace {
constexpr UINT width=320,height=180;
[[noreturn]] void Fail(const char* message){std::fprintf(stderr,"FAIL %s\n",message);ExitProcess(1);}
void Need(bool value,const char* message){if(!value)Fail(message);}
void Gpu(HRESULT hr,const char* message){if(FAILED(hr)){std::fprintf(stderr,"GPU HRESULT=%08lx %s\n",hr,message);Fail(message);}}
template<class T>T Value(Result<T> r,const char* message){if(!r){std::fprintf(stderr,"%s: %s\n",message,r.error().message.c_str());Fail(message);}return std::move(*r);}
void Done(Result<void> r,const char* message){if(!r){std::fprintf(stderr,"%s: %s\n",message,r.error().message.c_str());Fail(message);}}
template<class T>auto Collect(T& stage){if constexpr(requires{stage.CollectCompleted();})return stage.CollectCompleted();else return Result<uint32_t>{0};}
RuntimeExports::EvaluateFn nativeEvaluate;
std::vector<NVSDK_NGX_Parameter*> observedParameters;
uint32_t __cdecl Observe(ID3D12GraphicsCommandList* list,void* feature,NVSDK_NGX_Parameter* p,void* callback){observedParameters.push_back(p);return nativeEvaluate(list,feature,p,callback);}
struct Commands {
    ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;
    void Initialize(ID3D12Device* d){Gpu(d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)),"allocator");Gpu(d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list)),"list");}
};
void Barrier(ID3D12GraphicsCommandList* list,ID3D12Resource* resource,D3D12_RESOURCE_STATES from,D3D12_RESOURCE_STATES to){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={resource,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,from,to};list->ResourceBarrier(1,&b);}
ComPtr<ID3D12Resource> Texture(ID3D12Device* device,DXGI_FORMAT format,bool output=false){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;d.Width=width;d.Height=height;d.DepthOrArraySize=d.MipLevels=d.SampleDesc.Count=1;d.Format=format;d.Flags=output?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;D3D12_HEAP_PROPERTIES heap{};heap.Type=D3D12_HEAP_TYPE_DEFAULT;ComPtr<ID3D12Resource> resource;Gpu(device->CreateCommittedResource(&heap,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&resource)),"texture");return resource;}
struct Transfer {
    ComPtr<ID3D12Resource> buffer;D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};
    void Initialize(ID3D12Device* d,ID3D12Resource* texture,D3D12_HEAP_TYPE type){auto shape=texture->GetDesc();uint64_t bytes{};d->GetCopyableFootprints(&shape,0,1,0,&footprint,nullptr,nullptr,&bytes);D3D12_RESOURCE_DESC b{};b.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;b.Width=bytes;b.Height=b.DepthOrArraySize=b.MipLevels=b.SampleDesc.Count=1;b.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;D3D12_HEAP_PROPERTIES heap{};heap.Type=type;Gpu(d->CreateCommittedResource(&heap,D3D12_HEAP_FLAG_NONE,&b,type==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&buffer)),"transfer");}
    void Upload(ID3D12GraphicsCommandList* list,ID3D12Resource* texture,const void* data,size_t pitch){unsigned char* mapped{};Gpu(buffer->Map(0,nullptr,reinterpret_cast<void**>(&mapped)),"upload map");for(UINT y=0;y<height;++y)std::memcpy(mapped+footprint.Offset+y*footprint.Footprint.RowPitch,static_cast<const unsigned char*>(data)+y*pitch,pitch);buffer->Unmap(0,nullptr);D3D12_TEXTURE_COPY_LOCATION dst{},src{};dst.pResource=texture;dst.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;src.pResource=buffer.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;src.PlacedFootprint=footprint;list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);}
    void Copy(ID3D12GraphicsCommandList* list,ID3D12Resource* texture){D3D12_TEXTURE_COPY_LOCATION dst{},src{};src.pResource=texture;src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;dst.pResource=buffer.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint=footprint;list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);}
    std::vector<uint16_t> Read(){unsigned char* mapped{};Gpu(buffer->Map(0,nullptr,reinterpret_cast<void**>(&mapped)),"readback map");std::vector<uint16_t> result(width*height*4);for(UINT y=0;y<height;++y)std::memcpy(result.data()+y*width*4,mapped+footprint.Offset+y*footprint.Footprint.RowPitch,width*8);D3D12_RANGE noWrite{};buffer->Unmap(0,&noWrite);return result;}
};
struct Image {
    ImagePacket packet;std::array<Transfer,4> upload;Transfer readback;std::vector<uint16_t> pixels;
    void Initialize(ID3D12Device* d,ID3D12GraphicsCommandList* list,unsigned frame){
        packet.color=Texture(d,DXGI_FORMAT_R16G16B16A16_FLOAT);packet.depth=Texture(d,DXGI_FORMAT_R32_FLOAT);packet.motion=Texture(d,DXGI_FORMAT_R16G16_FLOAT);packet.output=Texture(d,DXGI_FORMAT_R16G16B16A16_FLOAT,true);
        pixels.resize(width*height*4);std::vector<uint16_t> motion(width*height*2),sentinel(pixels.size(),DirectX::PackedVector::XMConvertFloatToHalf(-.25f));std::vector<float> depth(width*height,.5f);
        for(UINT y=0;y<height;++y)for(UINT x=0;x<width;++x){auto i=(y*width+x)*4;pixels[i]=DirectX::PackedVector::XMConvertFloatToHalf(((x/8+y/8+frame)&1)?.15f:.85f);pixels[i+1]=DirectX::PackedVector::XMConvertFloatToHalf(float(x)/width+.01f*frame);pixels[i+2]=DirectX::PackedVector::XMConvertFloatToHalf(float(y)/height);pixels[i+3]=DirectX::PackedVector::XMConvertFloatToHalf(float((x+frame)%5)/4);}
        const std::array resources{packet.color.Get(),packet.depth.Get(),packet.motion.Get(),packet.output.Get()};const std::array<const void*,4> data{pixels.data(),depth.data(),motion.data(),sentinel.data()};const std::array<size_t,4> pitches{width*8,width*4,width*4,width*8};
        for(size_t i=0;i<4;++i){upload[i].Initialize(d,resources[i],D3D12_HEAP_TYPE_UPLOAD);upload[i].Upload(list,resources[i],data[i],pitches[i]);Barrier(list,resources[i],D3D12_RESOURCE_STATE_COPY_DEST,i==3?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);}
        readback.Initialize(d,packet.output.Get(),D3D12_HEAP_TYPE_READBACK);packet.epoch=packet.guideEpoch=1;packet.imageId=packet.batchId=packet.sourceId=packet.guideSourceId=frame+1;packet.previousSourceId=frame;packet.presentationTime=double(frame+1)/60;packet.interpolationFraction=1;packet.colorExtent=packet.guideExtent={width,height};packet.colorDomain=ColorDomain::Linear;packet.guideOrigin=GuideOrigin::RealSource;packet.motionScaleX=packet.motionScaleY=1;packet.reset=frame==0;packet.colorState=packet.depthState=packet.motionState=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;packet.outputState=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
    }
};
ComPtr<ID3D12Fence> Fence(ID3D12Device* d){ComPtr<ID3D12Fence> f;Gpu(d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)),"fence");return f;}
void Execute(ID3D12CommandQueue* queue,Commands& c){Gpu(c.list->Close(),"close");ID3D12CommandList* lists[]={c.list.Get()};queue->ExecuteCommandLists(1,lists);}
void Wait(ID3D12Device* d,ID3D12Fence* f,uint64_t value){auto event=CreateEventW(nullptr,FALSE,FALSE,nullptr);Need(event!=nullptr,"event");Gpu(f->SetEventOnCompletion(value,event),"arm");Need(WaitForSingleObject(event,20000)==WAIT_OBJECT_0&&f->GetCompletedValue()>=value,"genuine completion");CloseHandle(event);Gpu(d->GetDeviceRemovedReason(),"device healthy");}
}
int wmain(int argc,wchar_t** argv){
    setvbuf(stdout,nullptr,_IONBF,0);
    if(argc!=4)return 77;if(NrRuntimeResearch::GameRunningOrUnknown())return 1;
    ComPtr<IDXGIFactory6> factory;Gpu(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)),"factory");ComPtr<IDXGIAdapter1> adapter;DXGI_ADAPTER_DESC1 desc{};
    for(UINT i=0;;++i){ComPtr<IDXGIAdapter1> a;auto hr=factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&a));if(hr==DXGI_ERROR_NOT_FOUND)break;Gpu(hr,"adapter");Gpu(a->GetDesc1(&desc),"adapter description");if(desc.VendorId==0x10de&&desc.DeviceId==0x2702){adapter=a;break;}}if(!adapter)return 77;
    StageContract contract;contract.colorExtent=contract.guideExtent={width,height};contract.adapterLuid={desc.AdapterLuid.LowPart,desc.AdapterLuid.HighPart};Gpu(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&contract.device)),"device");D3D12_COMMAND_QUEUE_DESC q{};Gpu(contract.device->CreateCommandQueue(&q,IID_PPV_ARGS(&contract.queue)),"queue");
    auto owner=std::make_shared<RuntimeOwner>(RuntimeOwnerPaths{argv[1],argv[2],std::filesystem::absolute("nr-slots-cache"),true});Done(owner->Open(RuntimeCatalog()[1],contract.device.Get(),{desc.VendorId,desc.DeviceId,desc.SubSysId,contract.adapterLuid,false}),"runtime");nativeEvaluate=owner->Exports().evaluate;const_cast<RuntimeExports&>(owner->Exports()).evaluate=&Observe;
    PerformanceMetrics metrics;metrics.Enable(true);Stage stage;Done(stage.Initialize(owner,contract,0,&metrics),"stage");SettingsSnapshot settings;settings.enabled=true;settings.revision=1;settings.tuning.localToneStrength=0;
    std::array<Image,4> images;Commands upload;upload.Initialize(contract.device.Get());for(unsigned i=0;i<4;++i)images[i].Initialize(contract.device.Get(),upload.list.Get(),i);Execute(contract.queue.Get(),upload);auto uploaded=Fence(contract.device.Get());Gpu(contract.queue->Signal(uploaded.Get(),1),"upload signal");Wait(contract.device.Get(),uploaded.Get(),1);
    std::puts("PASS uploads retired");const bool serialSubmit=std::wstring_view(argv[3])==L"serial-submit";
    auto gate=Fence(contract.device.Get());if(!serialSubmit)Gpu(contract.queue->Wait(gate.Get(),1),"NR queue gate");
    std::array<Commands,4> evaluation,readers;std::array<ComPtr<ID3D12Fence>,4> done,readerGate,readerDone;std::array<ComPtr<ID3D12CommandQueue>,4> readerQueue;std::array<EvaluationTicket,4> tickets;
    for(unsigned i=0;i<3;++i){evaluation[i].Initialize(contract.device.Get());metrics.BeginFrame(i+1,true);tickets[i]=Value(stage.Record(evaluation[i].list.Get(),images[i].packet,settings),"ThreePendingTickets");Execute(contract.queue.Get(),evaluation[i]);done[i]=Fence(contract.device.Get());Done(stage.MarkSubmitted(tickets[i],done[i].Get(),1),"submit ticket");metrics.EndFrame();std::printf("recorded/submitted %u\n",i);if(serialSubmit){Wait(contract.device.Get(),done[i].Get(),1);std::printf("NR completed %u\n",i);}
        readerGate[i]=Fence(contract.device.Get());readerDone[i]=Fence(contract.device.Get());Gpu(contract.device->CreateCommandQueue(&q,IID_PPV_ARGS(&readerQueue[i])),"reader queue");readers[i].Initialize(contract.device.Get());Barrier(readers[i].list.Get(),images[i].packet.output.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);images[i].readback.Copy(readers[i].list.Get(),images[i].packet.output.Get());Gpu(readerQueue[i]->Wait(done[i].Get(),1),"reader NR wait");Gpu(readerQueue[i]->Wait(readerGate[i].Get(),1),"reader gate");Execute(readerQueue[i].Get(),readers[i]);Gpu(readerQueue[i]->Signal(readerDone[i].Get(),1),"real reader signal");Done(stage.TrackReader(tickets[i],readerDone[i].Get(),1),"retain reader");}
    evaluation[3].Initialize(contract.device.Get());auto fourth=stage.Record(evaluation[3].list.Get(),images[3].packet,settings);Need(!fourth&&fourth.error().kind==ErrorKind::Retirement,"FourthAdmissionBackpressure");Need(!stage.Retire(),"PendingReadersPreventRelease");
    Need(observedParameters.size()==3&&observedParameters[0]!=observedParameters[1]&&observedParameters[1]!=observedParameters[2]&&observedParameters[0]!=observedParameters[2],"ParametersPreservedPerSlot");for(unsigned i=0;i<3;++i){ID3D12Resource* color{};Need(uint32_t(observedParameters[i]->Get("DLSSNR.Color",&color))==1&&color==images[i].packet.color.Get(),"ParametersStillOwnOriginalImage");}
    Gpu(gate->Signal(1),"release NR gate");Wait(contract.device.Get(),done[2].Get(),1);Need(Value(Collect(stage),"collect")==0,"NrCompleteReaderPendingNotReused");Gpu(readerGate[1]->Signal(1),"release middle reader");Wait(contract.device.Get(),readerDone[1].Get(),1);Need(Value(Collect(stage),"collect middle")==1,"CompletedSlotCollectedIndividually");Need(!stage.TrackReader(tickets[1],readerDone[1].Get(),1)&&!stage.RetireTicket(tickets[1]),"RecycledTicketTokenRejected");
    auto alias=images[3].packet;alias.color=images[0].packet.color;Need(!stage.Record(evaluation[3].list.Get(),alias,settings),"OccupiedResourceAliasRejected");auto stale=images[3].packet;stale.epoch=stale.guideEpoch=0;Need(!stage.Record(evaluation[3].list.Get(),stale,settings),"StaleEpochRejected");metrics.BeginFrame(4,true);tickets[3]=Value(stage.Record(evaluation[3].list.Get(),images[3].packet,settings),"reuse middle slot");metrics.EndFrame();
    auto snapshots=metrics.Snapshot();Need(snapshots.frames.size()==4&&snapshots.frames[3].descriptorCreations==0,"DescriptorOwnerReusedOnlyAfterReader");
    if(std::wstring_view(argv[3])==L"unsubmitted"){auto next=images[1].packet;next.imageId=next.batchId=next.sourceId=next.guideSourceId=5;next.previousSourceId=4;next.presentationTime=5./60;Need(!stage.Record(evaluation[3].list.Get(),next,settings),"UnsubmittedCommandQuarantine");Need(!stage.Retire(),"UnsubmittedSlotCannotRelease");std::puts("PASS unsubmitted quarantine");ExitProcess(0);}
    Execute(contract.queue.Get(),evaluation[3]);done[3]=Fence(contract.device.Get());Done(stage.MarkSubmitted(tickets[3],done[3].Get(),1),"recycled submit");Wait(contract.device.Get(),done[3].Get(),1);
    for(unsigned i:{0u,2u}){Gpu(readerGate[i]->Signal(1),"release remaining reader");Wait(contract.device.Get(),readerDone[i].Get(),1);}Done(stage.RetireTicket(tickets[0]),"retire first");Done(stage.RetireTicket(tickets[2]),"retire third");Done(stage.RetireTicket(tickets[3]),"retire recycled");Done(stage.Retire(),"release pooled stage");
    Stage serial;Done(serial.Initialize(owner,contract),"serial reference");std::array<Image,3> references;Commands referenceUpload;referenceUpload.Initialize(contract.device.Get());for(unsigned i=0;i<3;++i)references[i].Initialize(contract.device.Get(),referenceUpload.list.Get(),i);Execute(contract.queue.Get(),referenceUpload);auto referenceReady=Fence(contract.device.Get());Gpu(contract.queue->Signal(referenceReady.Get(),1),"reference upload");Wait(contract.device.Get(),referenceReady.Get(),1);
    uint64_t alpha{};for(unsigned i=0;i<3;++i){Commands commands;commands.Initialize(contract.device.Get());auto ticket=Value(serial.Record(commands.list.Get(),references[i].packet,settings),"serial record");Barrier(commands.list.Get(),references[i].packet.output.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);references[i].readback.Copy(commands.list.Get(),references[i].packet.output.Get());Execute(contract.queue.Get(),commands);auto completed=Fence(contract.device.Get());Done(serial.MarkSubmitted(ticket,completed.Get(),1),"serial submitted");Wait(contract.device.Get(),completed.Get(),1);auto expected=references[i].readback.Read(),actual=images[i].readback.Read();Need(actual==expected,"MultiTicketSerialReferenceExactRgba");for(size_t p=3;p<actual.size();p+=4){Need(actual[p]==images[i].pixels[p],"source alpha exact");++alpha;}Done(serial.RetireTicket(ticket),"serial retirement");}
    Done(serial.Retire(),"serial release");Done(owner->Retire(),"runtime retirement");std::printf("PASS ThreePendingTickets FourthAdmissionBackpressure IndividualReaderRetirement ExactSerialRgba alpha=%llu\n",alpha);return 0;
}
