file(READ "${POLICY_FILE}" policy)
set(required_options "IPO=ON" "/Zc:__cplusplus" "/arch:AVX" "/W4")
# Single-config Ninja Release does not initialize a DEBUG property at all.
# Check the override in a Debug configuration, where it controls the build.
if(CONFIG STREQUAL "Debug")
    list(APPEND required_options "DebugIPO=OFF")
endif()
foreach(required IN LISTS required_options)
    string(FIND "${policy}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Plugin compiler policy missing ${required}: ${policy}")
    endif()
endforeach()
if(CONFIG STREQUAL "Release")
    string(FIND "${policy}" "/LTCG" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Release plugin linker has no /LTCG")
    endif()
endif()
message(STATUS "PASS: actual plugin IPO and MSVC flags")
