"""Generate the public INI templates, schema header and reference from schema.json."""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[2]


def choices(field):
    if field.get('codec') == 'MipLodBias': return ['Auto', 'numeric bias']
    if field.get('codec') == 'Hotkey': return ['End', 'Insert', 'Home', 'PageUp', 'PageDown', 'Delete', 'Tab', 'F1-F12', 'hex/decimal virtual-key code']
    if field.get('choices'): return field['choices']
    if field['type'] == 'Bool': return ['true', 'false']
    return list(field['values'])


def generate():
    schema = json.loads((ROOT / "tools/ini/schema.json").read_text(encoding="utf-8"))
    fields = schema["fields"]
    header = ['// Generated by tools/ini/Generate-Ini.py; edit tools/ini/schema.json.',
              '#pragma once', '#include <array>', '#include <span>', '#include <string_view>',
              'namespace TheosRenderPipeline::PublicIni {',
              'struct EnumValue { std::string_view publicValue, internalValue; };',
              'struct Field { const char* internalSection; const char* internalKey; const char* section; const char* key; const char* defaultValue; const char* type; const char* codec; const char* reference; bool inherit; std::span<const EnumValue> values; };',
              'struct RetiredInput { const char* section; const char* key; };',
              'inline constexpr std::array RetiredInputs{']
    for field in schema['retired_inputs']:
        header.append('    RetiredInput{' + json.dumps(field['section']) + ',' + json.dumps(field['key']) + '},')
    header.append('};')
    for index, field in enumerate(fields):
        if field["values"]:
            header.append(f'inline constexpr std::array enum{index}{{')
            for public, internal in field["values"].items():
                header.append('    EnumValue{' + json.dumps(public) + ',' + json.dumps(internal) + '},')
            header.append('};')
    header.append('inline constexpr std::array Fields{')
    for index, field in enumerate(fields):
        args = [field[k] for k in ['internal_section', 'internal_key', 'section', 'key', 'default', 'type']]
        args.append(field.get('codec', ''))
        args.append('[' + field['section'] + '] ' + field['key'])
        header.append('    Field{' + ','.join(json.dumps(s) for s in args) + ',' +
                      str(field.get('inherit', False)).lower() + ',' +
                      (f'enum{index}' if field['values'] else '{}') + '},')
    header += ['};',
               'inline constexpr const char* Reference(std::string_view section, std::string_view key) {',
               '    for (const auto& field : Fields) if (section == field.internalSection && key == field.internalKey) return field.reference;',
               '    return "[unknown]";', '}', '}']
    outputs = {ROOT / 'src/PublicIniSchema.h': '\n'.join(header) + '\n'}
    for example, overrides in [('package/SKSE/Plugins/RaZkolbaS.ini', {}),
                               ('package/examples/FSR-SR/RaZkolbaS.ini', {
                                   'Upscaling/Upscaler': 'FSR', 'FrameGeneration/Enabled': 'false',
                                   'FSR/SourceColorEncoding': 'Gamma22'}),
                               ('package/examples/FSR-FG/RaZkolbaS.ini', {
                                   'Upscaling/Upscaler': 'FSR', 'FrameGeneration/Enabled': 'true',
                                   'FSR/SourceColorEncoding': 'Gamma22'})]:
        lines = ['; RaZkolbaS settings. Current named layout only.',
                 '; [restart] marks settings that require Save and a Skyrim restart.',
                 '; Native selects output-resolution AA in [DLSS], [FSR] or [XeSS].',
                 '; FG Backend=Auto follows the upscaler; choose FSR to pair DLSS with FSR FG.',
                 '; NR After order: DLSS/FSR -> NR -> FG -> UI. XeSS SR trial requires NR, FG and HDR off.',
                 '; NR selects its bundled model from the rendering GPU automatically; manual overrides are diagnostic.',
                 '; Advanced and program-owned settings are grouped below ordinary options.']
        for section in schema['sections']:
            if section == 'Upscaling Advanced':
                lines += ['', '; ---- Advanced settings: change only when needed ----']
            if section == 'Menu':
                lines += ['', '; ---- Program-owned state ----']
            lines += ['', f'[{section}]']
            for field in (f for f in fields if f['section'] == section):
                names = ' | '.join(choices(field))
                note = ('[restart] ' if field['restart'] else '') + field['comment']
                lines += ['; ' + note]
                if names: lines += ['; Values: ' + names + '.']
                if field['type'] == 'Integer': lines += ['; Whole numbers only.']
                if field.get('range'): lines += ['; Range: ' + field['range'] + '.']
                lines += [(field['key'] + ' = ' + overrides.get(section + '/' + field['key'], field['default'])).rstrip()]
        outputs[ROOT / example] = '\n'.join(lines) + '\n'
    docs = ['# INI settings', '',
            'Edit `SKSE/Plugins/RaZkolbaS.ini`. This build reads the current named layout only; old files must be converted explicitly or replaced with the matching packaged INI. No ConfigVersion is needed.', '',
            '`[Upscaling] Upscaler` chooses DLSS or FSR. Both provider sections use `Quality=Native`. DLSS Native selects DLAA internally. Each provider retains its own quality and sharpness. FG on/off is live and keeps its presenter available. `[FrameGeneration] Backend=Auto` follows the upscaler; `FSR` also pairs DLSS/DLAA with FSR FG. Changing Backend requires Save and restart. FSR upscaling cannot use the NVIDIA presenter.', '',
            'FSR providers are independent: `[FSR] Provider=FSR4` requires ML upscaling, while `[FrameGeneration] FsrProvider=FSR4` requires ML frame generation. `Auto` allows the qualified analytical fallback. Explicit FSR4 reports an error when unavailable. FSR4 FG remains experimental. API versions in the log are not algorithm versions.', '',
            'FSR and NR source color encoding remain independent because they can process different pipeline formats. Do not infer encoding from texture format. Unknown prevents the corresponding feature from starting. Provider, runtime, encoding, quality and keys marked restart require Save and restart.', '',
            'Normal NR automatically selects its bundled model from the actual rendering adapter: RTX 20/30 use the compatibility model; RTX 40/50 share a model; AMD NR is unavailable. The former `[NeuralRendering Advanced] Runtime` selector is ignored and removed on save. `[NeuralRendering Advanced] Profile=Auto` selects the GPU family; explicit profiles, catalog/driver overrides and `[Debug] NRLegacyRuntime=true` are diagnostics. The Legacy implementation requires a separately installed runtime and is never an automatic fallback.', '',
            'The file stays organized as one INI: ordinary controls first, advanced settings below, program-owned menu geometry last. Linked NR passes retain their independent saved overrides so unlinking after a restart restores them. Unknown user keys and comments survive menu saves.', '',
            'Defaults and this table are generated from `tools/ini/schema.json` by `tools/ini/Generate-Ini.py`.', '',
            'To convert a previous organized INI, run `pwsh -NoProfile -File tools/ini/Reorganize-Ini.ps1 -SourceIni "old.ini" -OutputIni "named.ini"` from the source checkout. Choose a new output path; the source is never overwritten. Review the output before installing it with the matching DLL. Obsolete legacy aliases are discarded rather than promoted.', '',
            '| Section | Setting | Default | Restart | Meaning |', '|---|---|---|---|---|']
    for field in fields:
        description = field['comment']
        names = choices(field)
        if names: description += ' Values: ' + ', '.join(names) + '.'
        if field['type'] == 'Integer': description += ' Whole numbers only.'
        if field.get('range'): description += ' Range: ' + field['range'] + '.'
        docs.append(f"| {field['section']} | {field['key']} | `{field['default']}` | {'Yes' if field['restart'] else 'No'} | {description.replace('|', '/')} |")
    outputs[ROOT / 'package/INI-SETTINGS.md'] = '\n'.join(docs) + '\n'
    return outputs


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8-sig') != content: stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        print('Stale generated INI artifacts:\n' + '\n'.join(stale), file=sys.stderr)
        sys.exit(1)
    print('PASS: public schema, templates and reference agree' if args.check else 'Generated public INI artifacts')
