// Generated by tools/ini/Generate-Ini.py; edit tools/ini/schema.json.
#pragma once
#include <array>
#include <span>
#include <string_view>
namespace TheosRenderPipeline::PublicIni {
struct EnumValue { std::string_view publicValue, internalValue; };
struct Field { const char* internalSection; const char* internalKey; const char* section; const char* key; const char* defaultValue; const char* type; const char* codec; const char* reference; bool inherit; std::span<const EnumValue> values; };
struct RetiredInput { const char* section; const char* key; };
inline constexpr std::array RetiredInputs{
    RetiredInput{"Settings","EnableUpscaler"},
    RetiredInput{"Experimental","PureDarkFullDelegation"},
    RetiredInput{"Experimental","SourceDLSSGBackend"},
    RetiredInput{"Debug","AutoABTest"},
};
inline constexpr std::array enum0{
    EnumValue{"DLSS","0"},
    EnumValue{"FSR","4"},
};
inline constexpr std::array enum1{
    EnumValue{"Auto","true"},
    EnumValue{"Manual","false"},
};
inline constexpr std::array enum5{
    EnumValue{"Native","2"},
    EnumValue{"Quality","2"},
    EnumValue{"Balanced","1"},
    EnumValue{"Performance","0"},
    EnumValue{"UltraPerformance","3"},
    EnumValue{"UltraQuality","4"},
};
inline constexpr std::array enum6{
    EnumValue{"Default","0"},
    EnumValue{"E","5"},
    EnumValue{"F","6"},
    EnumValue{"J","10"},
    EnumValue{"K","11"},
    EnumValue{"L","12"},
    EnumValue{"M","13"},
};
inline constexpr std::array enum7{
    EnumValue{"Native","NativeAA"},
    EnumValue{"Quality","Quality"},
    EnumValue{"Balanced","Balanced"},
    EnumValue{"Performance","Performance"},
};
inline constexpr std::array enum8{
    EnumValue{"FSR3","Analytical"},
    EnumValue{"Auto","Compatible"},
    EnumValue{"FSR4","MachineLearning"},
};
inline constexpr std::array enum10{
    EnumValue{"Unknown","Unknown"},
    EnumValue{"Linear","Linear"},
    EnumValue{"Gamma22","Gamma22"},
    EnumValue{"SRGB","SRGB"},
};
inline constexpr std::array enum11{
    EnumValue{"Auto","0"},
    EnumValue{"NVIDIA","1"},
    EnumValue{"FSR","2"},
};
inline constexpr std::array enum13{
    EnumValue{"FSR3","Analytical"},
    EnumValue{"Auto","Compatible"},
    EnumValue{"FSR4","MachineLearning"},
};
inline constexpr std::array enum19{
    EnumValue{"Off","0"},
    EnumValue{"On","1"},
    EnumValue{"Boost","2"},
};
inline constexpr std::array enum22{
    EnumValue{"Dedicated","0"},
    EnumValue{"HudlessDetection","1"},
};
inline constexpr std::array enum24{
    EnumValue{"Before","true"},
    EnumValue{"After","false"},
};
inline constexpr std::array enum52{
    EnumValue{"End","0x23"},
};
inline constexpr std::array enum58{
    EnumValue{"Legacy","false"},
    EnumValue{"Community","true"},
};
inline constexpr std::array enum59{
    EnumValue{"Auto","Auto"},
    EnumValue{"rtx20-30","rtx20-30"},
    EnumValue{"rtx40","rtx40"},
    EnumValue{"rtx50","rtx50"},
};
inline constexpr std::array enum60{
    EnumValue{"Unknown","Unknown"},
    EnumValue{"Linear","Linear"},
    EnumValue{"Gamma22","Gamma22"},
    EnumValue{"SRGB","SRGB"},
};
inline constexpr std::array enum64{
    EnumValue{"Auto","0"},
    EnumValue{"Residual","1"},
    EnumValue{"Ratio","2"},
};
inline constexpr std::array enum83{
    EnumValue{"Gamma22","0"},
    EnumValue{"SRGB","1"},
};
inline constexpr std::array Fields{
    Field{"Settings","UpscaleType","Upscaling","Upscaler","DLSS","Enum","","[Upscaling] Upscaler",false,enum0},
    Field{"Settings","UseOptimalMipLodBias","Upscaling","MipLodBias","Auto","Enum","MipLodBias","[Upscaling] MipLodBias",false,enum1},
    Field{"Settings","EnableJitter","Upscaling","EnableJitter","true","Bool","","[Upscaling] EnableJitter",false,{}},
    Field{"Settings","AutoExposure","Upscaling","AutoExposure","true","Bool","","[Upscaling] AutoExposure",false,{}},
    Field{"Settings","Sharpness","DLSS","Sharpness","0.672","Number","","[DLSS] Sharpness",false,{}},
    Field{"DLSS","QualityLevel","DLSS","Quality","Native","Enum","","[DLSS] Quality",false,enum5},
    Field{"DLSS","Preset","DLSS","Preset","K","Enum","","[DLSS] Preset",false,enum6},
    Field{"FSR","Quality","FSR","Quality","Native","Enum","","[FSR] Quality",false,enum7},
    Field{"FSR","ProviderPolicy","FSR","Provider","FSR3","Enum","","[FSR] Provider",false,enum8},
    Field{"FSR","Sharpness","FSR","Sharpness","0.0","Number","","[FSR] Sharpness",false,{}},
    Field{"FSR","SourceColorEncoding","FSR","SourceColorEncoding","Unknown","Text","","[FSR] SourceColorEncoding",false,enum10},
    Field{"FrameGeneration","BackendPreference","FrameGeneration","Backend","Auto","Enum","","[FrameGeneration] Backend",false,enum11},
    Field{"FrameGeneration","Enabled","FrameGeneration","Enabled","true","Bool","","[FrameGeneration] Enabled",false,{}},
    Field{"FrameGeneration","FsrProviderPolicy","FrameGeneration","FsrProvider","FSR3","Enum","","[FrameGeneration] FsrProvider",false,enum13},
    Field{"FrameGeneration","GeneratedFrames","FrameGeneration","NvidiaGeneratedFrames","1","Integer","","[FrameGeneration] NvidiaGeneratedFrames",false,{}},
    Field{"FrameGeneration","DynamicMFG","FrameGeneration","NvidiaDynamicMFG","false","Bool","","[FrameGeneration] NvidiaDynamicMFG",false,{}},
    Field{"FrameGeneration","DynamicTargetFPS","FrameGeneration","DynamicTargetFPS","0","Integer","","[FrameGeneration] DynamicTargetFPS",false,{}},
    Field{"FrameGeneration","UIRecomposition","FrameGeneration","NvidiaUIRecomposition","true","Bool","","[FrameGeneration] NvidiaUIRecomposition",false,{}},
    Field{"FrameGeneration","OutputFPSLimit","Latency","OutputFPSLimit","0","Integer","","[Latency] OutputFPSLimit",false,{}},
    Field{"FrameGeneration","ReflexMode","Latency","Reflex","On","Enum","","[Latency] Reflex",false,enum19},
    Field{"Settings","NativeUI","Interface","NativeUI","true","Bool","","[Interface] NativeUI",false,{}},
    Field{"Settings","RequestLoadingArtwork","Interface","RequestLoadingArtwork","true","Bool","","[Interface] RequestLoadingArtwork",false,{}},
    Field{"FrameGeneration","UICompositionMode","Interface","UIComposition","Dedicated","Enum","","[Interface] UIComposition",false,enum22},
    Field{"NeuralRendering","Enabled","NeuralRendering","Enabled","false","Bool","","[NeuralRendering] Enabled",false,{}},
    Field{"NeuralRendering","BeforeUpscaling","NeuralRendering","Placement","Before","Enum","","[NeuralRendering] Placement",false,enum24},
    Field{"NeuralRendering","PassCount","NeuralRendering","PassCount","1","Integer","","[NeuralRendering] PassCount",false,{}},
    Field{"NeuralRendering","OnePassInCombat","NeuralRendering","OnePassInCombat","false","Bool","","[NeuralRendering] OnePassInCombat",false,{}},
    Field{"NeuralRendering","OnePassWeaponsDrawn","NeuralRendering","OnePassWeaponsDrawn","false","Bool","","[NeuralRendering] OnePassWeaponsDrawn",false,{}},
    Field{"NeuralRendering","PassRecoverySeconds","NeuralRendering","PassRecoverySeconds","5","Number","","[NeuralRendering] PassRecoverySeconds",false,{}},
    Field{"NR PASS 1","Style","NR PASS 1","Style","0","Integer","","[NR PASS 1] Style",false,{}},
    Field{"NR PASS 1","Intensity","NR PASS 1","Intensity","1.0","Number","","[NR PASS 1] Intensity",false,{}},
    Field{"NR PASS 1","Tone","NR PASS 1","Tone","1.0","Number","","[NR PASS 1] Tone",false,{}},
    Field{"NR PASS 1","Structure","NR PASS 1","Structure","1.0","Number","","[NR PASS 1] Structure",false,{}},
    Field{"NR PASS 1","SkinStructure","NR PASS 1","SkinStructure","1.0","Number","","[NR PASS 1] SkinStructure",false,{}},
    Field{"NR PASS 1","AutoSkin","NR PASS 1","AutoSkin","false","Bool","","[NR PASS 1] AutoSkin",false,{}},
    Field{"NR PASS 1","UICorrection","NR PASS 1","UICorrection","false","Bool","","[NR PASS 1] UICorrection",false,{}},
    Field{"NR PASS 2","UseSameSettings","NR PASS 2","UseSameSettings","true","Bool","","[NR PASS 2] UseSameSettings",false,{}},
    Field{"NR PASS 2","Style","NR PASS 2","Style","0","Integer","","[NR PASS 2] Style",true,{}},
    Field{"NR PASS 2","Intensity","NR PASS 2","Intensity","1.0","Number","","[NR PASS 2] Intensity",true,{}},
    Field{"NR PASS 2","Tone","NR PASS 2","Tone","1.0","Number","","[NR PASS 2] Tone",true,{}},
    Field{"NR PASS 2","Structure","NR PASS 2","Structure","1.0","Number","","[NR PASS 2] Structure",true,{}},
    Field{"NR PASS 2","SkinStructure","NR PASS 2","SkinStructure","1.0","Number","","[NR PASS 2] SkinStructure",true,{}},
    Field{"NR PASS 2","AutoSkin","NR PASS 2","AutoSkin","false","Bool","","[NR PASS 2] AutoSkin",true,{}},
    Field{"NR PASS 2","UICorrection","NR PASS 2","UICorrection","false","Bool","","[NR PASS 2] UICorrection",true,{}},
    Field{"NR PASS 3","UseSameSettings","NR PASS 3","UseSameSettings","true","Bool","","[NR PASS 3] UseSameSettings",false,{}},
    Field{"NR PASS 3","Style","NR PASS 3","Style","0","Integer","","[NR PASS 3] Style",true,{}},
    Field{"NR PASS 3","Intensity","NR PASS 3","Intensity","1.0","Number","","[NR PASS 3] Intensity",true,{}},
    Field{"NR PASS 3","Tone","NR PASS 3","Tone","1.0","Number","","[NR PASS 3] Tone",true,{}},
    Field{"NR PASS 3","Structure","NR PASS 3","Structure","1.0","Number","","[NR PASS 3] Structure",true,{}},
    Field{"NR PASS 3","SkinStructure","NR PASS 3","SkinStructure","1.0","Number","","[NR PASS 3] SkinStructure",true,{}},
    Field{"NR PASS 3","AutoSkin","NR PASS 3","AutoSkin","false","Bool","","[NR PASS 3] AutoSkin",true,{}},
    Field{"NR PASS 3","UICorrection","NR PASS 3","UICorrection","false","Bool","","[NR PASS 3] UICorrection",true,{}},
    Field{"Hotkeys","ToggleOverlay","Hotkeys","ToggleOverlay","End","Enum","Hotkey","[Hotkeys] ToggleOverlay",false,enum52},
    Field{"Hotkeys","EnableNRHotkeys","Hotkeys","EnableNRHotkeys","false","Bool","","[Hotkeys] EnableNRHotkeys",false,{}},
    Field{"Appearance","Enabled","Appearance","Enabled","false","Bool","","[Appearance] Enabled",false,{}},
    Field{"Appearance","SmoothingSeconds","Appearance","SmoothingSeconds","2.0","Number","","[Appearance] SmoothingSeconds",false,{}},
    Field{"Appearance","WeatherCount","Appearance","WeatherCount","0","Integer","","[Appearance] WeatherCount",false,{}},
    Field{"Experimental","FsrOrdinaryPresenter","Upscaling Advanced","FsrOrdinaryPresenter","false","Bool","","[Upscaling Advanced] FsrOrdinaryPresenter",false,{}},
    Field{"NeuralRendering","CommunityRuntime","NeuralRendering Advanced","Runtime","Legacy","Enum","","[NeuralRendering Advanced] Runtime",false,enum58},
    Field{"NeuralRendering","Profile","NeuralRendering Advanced","Profile","Auto","Text","","[NeuralRendering Advanced] Profile",false,enum59},
    Field{"NeuralRendering","SourceColorEncoding","NeuralRendering Advanced","SourceColorEncoding","Unknown","Text","","[NeuralRendering Advanced] SourceColorEncoding",false,enum60},
    Field{"NeuralRendering","SdrBytesTrial","NeuralRendering Advanced","SdrBytesTrial","false","Bool","","[NeuralRendering Advanced] SdrBytesTrial",false,{}},
    Field{"NR PASS 1","Preset","NR PASS 1 Advanced","Preset","0","Integer","","[NR PASS 1 Advanced] Preset",false,{}},
    Field{"NR PASS 1","InputScale","NR PASS 1 Advanced","InputScale","1.0","Number","","[NR PASS 1 Advanced] InputScale",false,{}},
    Field{"NR PASS 1","ResolveMethod","NR PASS 1 Advanced","ResolveMethod","Auto","Enum","","[NR PASS 1 Advanced] ResolveMethod",false,enum64},
    Field{"NR PASS 1","TransferStrength","NR PASS 1 Advanced","TransferStrength","1.0","Number","","[NR PASS 1 Advanced] TransferStrength",false,{}},
    Field{"NR PASS 1","ColourStrength","NR PASS 1 Advanced","ColourStrength","1.0","Number","","[NR PASS 1 Advanced] ColourStrength",false,{}},
    Field{"NR PASS 1","MaxRatio","NR PASS 1 Advanced","MaxRatio","2.0","Number","","[NR PASS 1 Advanced] MaxRatio",false,{}},
    Field{"NR PASS 1","WhitePoint","NR PASS 1 Advanced","WhitePoint","1.0","Number","","[NR PASS 1 Advanced] WhitePoint",false,{}},
    Field{"NR PASS 1","ColorIsHDR","NR PASS 1 Advanced","ColorIsHDR","false","Bool","","[NR PASS 1 Advanced] ColorIsHDR",false,{}},
    Field{"NR PASS 1","PeripheralCompression","NR PASS 1 Advanced","PeripheralCompression","false","Bool","","[NR PASS 1 Advanced] PeripheralCompression",false,{}},
    Field{"NR PASS 1","FusedPreparation","NR PASS 1 Advanced","FusedPreparation","false","Bool","","[NR PASS 1 Advanced] FusedPreparation",false,{}},
    Field{"NR PASS 2","Preset","NR PASS 2 Advanced","Preset","0","Integer","","[NR PASS 2 Advanced] Preset",true,{}},
    Field{"NR PASS 2","InputScale","NR PASS 2 Advanced","InputScale","1.0","Number","","[NR PASS 2 Advanced] InputScale",true,{}},
    Field{"NR PASS 3","Preset","NR PASS 3 Advanced","Preset","0","Integer","","[NR PASS 3 Advanced] Preset",true,{}},
    Field{"NR PASS 3","InputScale","NR PASS 3 Advanced","InputScale","1.0","Number","","[NR PASS 3 Advanced] InputScale",true,{}},
    Field{"HDROutput","Enabled","HDROutput","Enabled","false","Bool","","[HDROutput] Enabled",false,{}},
    Field{"HDROutput","MatchWindowsSDRBrightness","HDROutput","MatchWindowsSDRBrightness","true","Bool","","[HDROutput] MatchWindowsSDRBrightness",false,{}},
    Field{"HDROutput","PaperWhiteNits","HDROutput","PaperWhiteNits","200","Number","","[HDROutput] PaperWhiteNits",false,{}},
    Field{"HDROutput","PeakNits","HDROutput","PeakNits","1000","Number","","[HDROutput] PeakNits",false,{}},
    Field{"HDROutput","UIBrightnessNits","HDROutput","UIBrightnessNits","200","Number","","[HDROutput] UIBrightnessNits",false,{}},
    Field{"HDROutput","HighlightStrength","HDROutput","HighlightStrength","1","Number","","[HDROutput] HighlightStrength",false,{}},
    Field{"HDROutput","ExpansionStart","HDROutput","ExpansionStart","0.7","Number","","[HDROutput] ExpansionStart",false,{}},
    Field{"HDROutput","SDRTransfer","HDROutput","SDRTransfer","Gamma22","Enum","","[HDROutput] SDRTransfer",false,enum83},
    Field{"Compatibility","ReShadeBeforeUpscaling","Compatibility","ReShadeBeforeUpscaling","false","Bool","","[Compatibility] ReShadeBeforeUpscaling",false,{}},
    Field{"Compatibility","WheelerLateOverlayBridge","Compatibility","WheelerLateOverlayBridge","true","Bool","","[Compatibility] WheelerLateOverlayBridge",false,{}},
    Field{"Compatibility","NvidiaMFGUnlock","Compatibility","NvidiaMFGUnlock","true","Bool","","[Compatibility] NvidiaMFGUnlock",false,{}},
    Field{"Runtime","StreamlineDirectory","Runtime","StreamlineDirectory","RaZkolbaS/NVIDIA/Streamline","Text","","[Runtime] StreamlineDirectory",false,{}},
    Field{"Runtime","NRRuntimePath","Runtime","NRRuntimePath","RaZkolbaS/NVIDIA/nvngx_dlssnr.dll","Text","","[Runtime] NRRuntimePath",false,{}},
    Field{"Runtime","NRRuntimeRoot","Runtime","NRRuntimeRoot","","Text","","[Runtime] NRRuntimeRoot",false,{}},
    Field{"Runtime","NRDriverCore","Runtime","NRDriverCore","","Text","","[Runtime] NRDriverCore",false,{}},
    Field{"DynamicResolution","Enabled","DynamicResolution","Enabled","false","Bool","","[DynamicResolution] Enabled",false,{}},
    Field{"DynamicResolution","Oscillate","DynamicResolution","Oscillate","false","Bool","","[DynamicResolution] Oscillate",false,{}},
    Field{"Performance","EnableGPUTimings","Debug","EnableGPUTimings","true","Bool","","[Debug] EnableGPUTimings",false,{}},
    Field{"Performance","EnableFrameTrace","Debug","EnableFrameTrace","false","Bool","","[Debug] EnableFrameTrace",false,{}},
    Field{"Performance","DirectRCASOutput","Debug","DirectRCASOutput","false","Bool","","[Debug] DirectRCASOutput",false,{}},
    Field{"Performance","DirectDLSSOutput","Debug","DirectDLSSOutput","false","Bool","","[Debug] DirectDLSSOutput",false,{}},
    Field{"Debug","LogFrameDiagnostics","Debug","LogFrameDiagnostics","false","Bool","","[Debug] LogFrameDiagnostics",false,{}},
    Field{"Debug","LogPerformanceMetrics","Debug","LogPerformanceMetrics","false","Bool","","[Debug] LogPerformanceMetrics",false,{}},
    Field{"Debug","PerformanceLogIntervalSeconds","Debug","PerformanceLogIntervalSeconds","10","Integer","","[Debug] PerformanceLogIntervalSeconds",false,{}},
    Field{"Debug","LogMenuMetrics","Debug","LogMenuMetrics","false","Bool","","[Debug] LogMenuMetrics",false,{}},
    Field{"Menu","WindowX","Menu","WindowX","40","Number","","[Menu] WindowX",false,{}},
    Field{"Menu","WindowY","Menu","WindowY","40","Number","","[Menu] WindowY",false,{}},
    Field{"Menu","WindowWidth","Menu","WindowWidth","640","Number","","[Menu] WindowWidth",false,{}},
    Field{"Menu","WindowHeight","Menu","WindowHeight","720","Number","","[Menu] WindowHeight",false,{}},
    Field{"Menu","LeftColumnFraction","Menu","LeftColumnFraction","0.5","Number","","[Menu] LeftColumnFraction",false,{}},
};
inline constexpr const char* Reference(std::string_view section, std::string_view key) {
    for (const auto& field : Fields) if (section == field.internalSection && key == field.internalKey) return field.reference;
    return "[unknown]";
}
}
