// Generated by tools/ini/Generate-Ini.py; edit tools/ini/schema.json.
#pragma once
#include <array>
#include <span>
#include <string_view>
namespace TheosRenderPipeline::PublicIni {
struct EnumValue { std::string_view publicValue, internalValue; };
struct Field { const char* internalSection; const char* internalKey; const char* section; const char* key; const char* defaultValue; const char* type; const char* codec; bool inherit; std::span<const EnumValue> values; };
inline constexpr std::array enum0{
    EnumValue{"DLSS","0"},
    EnumValue{"FSR","4"},
};
inline constexpr std::array enum1{
    EnumValue{"Auto","true"},
    EnumValue{"Manual","false"},
};
inline constexpr std::array enum5{
    EnumValue{"Native","2"},
    EnumValue{"Quality","2"},
    EnumValue{"Balanced","1"},
    EnumValue{"Performance","0"},
    EnumValue{"UltraPerformance","3"},
    EnumValue{"UltraQuality","4"},
};
inline constexpr std::array enum6{
    EnumValue{"Default","0"},
    EnumValue{"E","5"},
    EnumValue{"F","6"},
    EnumValue{"J","10"},
    EnumValue{"K","11"},
    EnumValue{"L","12"},
    EnumValue{"M","13"},
};
inline constexpr std::array enum7{
    EnumValue{"Native","NativeAA"},
    EnumValue{"Quality","Quality"},
    EnumValue{"Balanced","Balanced"},
    EnumValue{"Performance","Performance"},
};
inline constexpr std::array enum8{
    EnumValue{"FSR3","Analytical"},
    EnumValue{"Auto","Compatible"},
    EnumValue{"FSR4","MachineLearning"},
};
inline constexpr std::array enum12{
    EnumValue{"FSR3","Analytical"},
    EnumValue{"Auto","Compatible"},
    EnumValue{"FSR4","MachineLearning"},
};
inline constexpr std::array enum18{
    EnumValue{"Off","0"},
    EnumValue{"On","1"},
    EnumValue{"Boost","2"},
};
inline constexpr std::array enum21{
    EnumValue{"Dedicated","0"},
    EnumValue{"HudlessDetection","1"},
};
inline constexpr std::array enum23{
    EnumValue{"Before","true"},
    EnumValue{"After","false"},
};
inline constexpr std::array enum51{
    EnumValue{"End","0x23"},
};
inline constexpr std::array enum57{
    EnumValue{"Legacy","false"},
    EnumValue{"Community","true"},
};
inline constexpr std::array enum63{
    EnumValue{"Auto","0"},
    EnumValue{"Residual","1"},
    EnumValue{"Ratio","2"},
};
inline constexpr std::array enum82{
    EnumValue{"Gamma22","0"},
    EnumValue{"SRGB","1"},
};
inline constexpr std::array Fields{
    Field{"Settings","UpscaleType","Upscaling","Upscaler","DLSS","Enum","",false,enum0},
    Field{"Settings","UseOptimalMipLodBias","Upscaling","MipLodBias","Auto","Enum","MipLodBias",false,enum1},
    Field{"Settings","EnableJitter","Upscaling","EnableJitter","true","Bool","",false,{}},
    Field{"Settings","AutoExposure","Upscaling","AutoExposure","true","Bool","",false,{}},
    Field{"Settings","Sharpness","DLSS","Sharpness","0.672","Number","",false,{}},
    Field{"DLSS","QualityLevel","DLSS","Quality","Native","Enum","",false,enum5},
    Field{"DLSS","Preset","DLSS","Preset","K","Enum","",false,enum6},
    Field{"FSR","Quality","FSR","Quality","Native","Enum","",false,enum7},
    Field{"FSR","ProviderPolicy","FSR","Provider","FSR3","Enum","",false,enum8},
    Field{"FSR","Sharpness","FSR","Sharpness","0.0","Number","",false,{}},
    Field{"FSR","SourceColorEncoding","FSR","SourceColorEncoding","Unknown","Text","",false,{}},
    Field{"FrameGeneration","Enabled","FrameGeneration","Enabled","true","Bool","",false,{}},
    Field{"FrameGeneration","FsrProviderPolicy","FrameGeneration","FsrProvider","FSR3","Enum","",false,enum12},
    Field{"FrameGeneration","GeneratedFrames","FrameGeneration","NvidiaGeneratedFrames","1","Number","",false,{}},
    Field{"FrameGeneration","DynamicMFG","FrameGeneration","NvidiaDynamicMFG","false","Bool","",false,{}},
    Field{"FrameGeneration","DynamicTargetFPS","FrameGeneration","DynamicTargetFPS","0","Number","",false,{}},
    Field{"FrameGeneration","UIRecomposition","FrameGeneration","NvidiaUIRecomposition","true","Bool","",false,{}},
    Field{"FrameGeneration","OutputFPSLimit","Latency","OutputFPSLimit","0","Number","",false,{}},
    Field{"FrameGeneration","ReflexMode","Latency","Reflex","On","Enum","",false,enum18},
    Field{"Settings","NativeUI","Interface","NativeUI","true","Bool","",false,{}},
    Field{"Settings","RequestLoadingArtwork","Interface","RequestLoadingArtwork","true","Bool","",false,{}},
    Field{"FrameGeneration","UICompositionMode","Interface","UIComposition","Dedicated","Enum","",false,enum21},
    Field{"NeuralRendering","Enabled","NeuralRendering","Enabled","false","Bool","",false,{}},
    Field{"NeuralRendering","BeforeUpscaling","NeuralRendering","Placement","Before","Enum","",false,enum23},
    Field{"NeuralRendering","PassCount","NeuralRendering","PassCount","1","Number","",false,{}},
    Field{"NeuralRendering","OnePassInCombat","NeuralRendering","OnePassInCombat","false","Bool","",false,{}},
    Field{"NeuralRendering","OnePassWeaponsDrawn","NeuralRendering","OnePassWeaponsDrawn","false","Bool","",false,{}},
    Field{"NeuralRendering","PassRecoverySeconds","NeuralRendering","PassRecoverySeconds","5","Number","",false,{}},
    Field{"NR PASS 1","Style","NR PASS 1","Style","0","Number","",false,{}},
    Field{"NR PASS 1","Intensity","NR PASS 1","Intensity","1.0","Number","",false,{}},
    Field{"NR PASS 1","Tone","NR PASS 1","Tone","1.0","Number","",false,{}},
    Field{"NR PASS 1","Structure","NR PASS 1","Structure","1.0","Number","",false,{}},
    Field{"NR PASS 1","SkinStructure","NR PASS 1","SkinStructure","1.0","Number","",false,{}},
    Field{"NR PASS 1","AutoSkin","NR PASS 1","AutoSkin","false","Bool","",false,{}},
    Field{"NR PASS 1","UICorrection","NR PASS 1","UICorrection","false","Bool","",false,{}},
    Field{"NR PASS 2","UseSameSettings","NR PASS 2","UseSameSettings","true","Bool","",false,{}},
    Field{"NR PASS 2","Style","NR PASS 2","Style","0","Number","",true,{}},
    Field{"NR PASS 2","Intensity","NR PASS 2","Intensity","1.0","Number","",true,{}},
    Field{"NR PASS 2","Tone","NR PASS 2","Tone","1.0","Number","",true,{}},
    Field{"NR PASS 2","Structure","NR PASS 2","Structure","1.0","Number","",true,{}},
    Field{"NR PASS 2","SkinStructure","NR PASS 2","SkinStructure","1.0","Number","",true,{}},
    Field{"NR PASS 2","AutoSkin","NR PASS 2","AutoSkin","false","Bool","",true,{}},
    Field{"NR PASS 2","UICorrection","NR PASS 2","UICorrection","false","Bool","",true,{}},
    Field{"NR PASS 3","UseSameSettings","NR PASS 3","UseSameSettings","true","Bool","",false,{}},
    Field{"NR PASS 3","Style","NR PASS 3","Style","0","Number","",true,{}},
    Field{"NR PASS 3","Intensity","NR PASS 3","Intensity","1.0","Number","",true,{}},
    Field{"NR PASS 3","Tone","NR PASS 3","Tone","1.0","Number","",true,{}},
    Field{"NR PASS 3","Structure","NR PASS 3","Structure","1.0","Number","",true,{}},
    Field{"NR PASS 3","SkinStructure","NR PASS 3","SkinStructure","1.0","Number","",true,{}},
    Field{"NR PASS 3","AutoSkin","NR PASS 3","AutoSkin","false","Bool","",true,{}},
    Field{"NR PASS 3","UICorrection","NR PASS 3","UICorrection","false","Bool","",true,{}},
    Field{"Hotkeys","ToggleOverlay","Hotkeys","ToggleOverlay","End","Enum","Hotkey",false,enum51},
    Field{"Hotkeys","EnableNRHotkeys","Hotkeys","EnableNRHotkeys","false","Bool","",false,{}},
    Field{"Appearance","Enabled","Appearance","Enabled","false","Bool","",false,{}},
    Field{"Appearance","SmoothingSeconds","Appearance","SmoothingSeconds","2.0","Number","",false,{}},
    Field{"Appearance","WeatherCount","Appearance","WeatherCount","0","Number","",false,{}},
    Field{"Experimental","FsrOrdinaryPresenter","Upscaling Advanced","FsrOrdinaryPresenter","false","Bool","",false,{}},
    Field{"NeuralRendering","CommunityRuntime","NeuralRendering Advanced","Runtime","Legacy","Enum","",false,enum57},
    Field{"NeuralRendering","Profile","NeuralRendering Advanced","Profile","Auto","Text","",false,{}},
    Field{"NeuralRendering","SourceColorEncoding","NeuralRendering Advanced","SourceColorEncoding","Unknown","Text","",false,{}},
    Field{"NeuralRendering","SdrBytesTrial","NeuralRendering Advanced","SdrBytesTrial","false","Bool","",false,{}},
    Field{"NR PASS 1","Preset","NR PASS 1 Advanced","Preset","0","Number","",false,{}},
    Field{"NR PASS 1","InputScale","NR PASS 1 Advanced","InputScale","1.0","Number","",false,{}},
    Field{"NR PASS 1","ResolveMethod","NR PASS 1 Advanced","ResolveMethod","Auto","Enum","",false,enum63},
    Field{"NR PASS 1","TransferStrength","NR PASS 1 Advanced","TransferStrength","1.0","Number","",false,{}},
    Field{"NR PASS 1","ColourStrength","NR PASS 1 Advanced","ColourStrength","1.0","Number","",false,{}},
    Field{"NR PASS 1","MaxRatio","NR PASS 1 Advanced","MaxRatio","2.0","Number","",false,{}},
    Field{"NR PASS 1","WhitePoint","NR PASS 1 Advanced","WhitePoint","1.0","Number","",false,{}},
    Field{"NR PASS 1","ColorIsHDR","NR PASS 1 Advanced","ColorIsHDR","false","Bool","",false,{}},
    Field{"NR PASS 1","PeripheralCompression","NR PASS 1 Advanced","PeripheralCompression","false","Bool","",false,{}},
    Field{"NR PASS 1","FusedPreparation","NR PASS 1 Advanced","FusedPreparation","false","Bool","",false,{}},
    Field{"NR PASS 2","Preset","NR PASS 2 Advanced","Preset","0","Number","",true,{}},
    Field{"NR PASS 2","InputScale","NR PASS 2 Advanced","InputScale","1.0","Number","",true,{}},
    Field{"NR PASS 3","Preset","NR PASS 3 Advanced","Preset","0","Number","",true,{}},
    Field{"NR PASS 3","InputScale","NR PASS 3 Advanced","InputScale","1.0","Number","",true,{}},
    Field{"HDROutput","Enabled","HDROutput","Enabled","false","Bool","",false,{}},
    Field{"HDROutput","MatchWindowsSDRBrightness","HDROutput","MatchWindowsSDRBrightness","true","Bool","",false,{}},
    Field{"HDROutput","PaperWhiteNits","HDROutput","PaperWhiteNits","200","Number","",false,{}},
    Field{"HDROutput","PeakNits","HDROutput","PeakNits","1000","Number","",false,{}},
    Field{"HDROutput","UIBrightnessNits","HDROutput","UIBrightnessNits","200","Number","",false,{}},
    Field{"HDROutput","HighlightStrength","HDROutput","HighlightStrength","1","Number","",false,{}},
    Field{"HDROutput","ExpansionStart","HDROutput","ExpansionStart","0.7","Number","",false,{}},
    Field{"HDROutput","SDRTransfer","HDROutput","SDRTransfer","Gamma22","Enum","",false,enum82},
    Field{"Compatibility","ReShadeBeforeUpscaling","Compatibility","ReShadeBeforeUpscaling","false","Bool","",false,{}},
    Field{"Compatibility","WheelerLateOverlayBridge","Compatibility","WheelerLateOverlayBridge","true","Bool","",false,{}},
    Field{"Compatibility","NvidiaMFGUnlock","Compatibility","NvidiaMFGUnlock","true","Bool","",false,{}},
    Field{"Runtime","StreamlineDirectory","Runtime","StreamlineDirectory","RaZkolbaS/NVIDIA/Streamline","Text","",false,{}},
    Field{"Runtime","NRRuntimePath","Runtime","NRRuntimePath","RaZkolbaS/NVIDIA/nvngx_dlssnr.dll","Text","",false,{}},
    Field{"Runtime","NRRuntimeRoot","Runtime","NRRuntimeRoot","","Text","",false,{}},
    Field{"Runtime","NRDriverCore","Runtime","NRDriverCore","","Text","",false,{}},
    Field{"DynamicResolution","Enabled","DynamicResolution","Enabled","false","Bool","",false,{}},
    Field{"DynamicResolution","Oscillate","DynamicResolution","Oscillate","false","Bool","",false,{}},
    Field{"Performance","EnableGPUTimings","Debug","EnableGPUTimings","true","Bool","",false,{}},
    Field{"Performance","EnableFrameTrace","Debug","EnableFrameTrace","false","Bool","",false,{}},
    Field{"Performance","DirectRCASOutput","Debug","DirectRCASOutput","false","Bool","",false,{}},
    Field{"Performance","DirectDLSSOutput","Debug","DirectDLSSOutput","false","Bool","",false,{}},
    Field{"Debug","LogFrameDiagnostics","Debug","LogFrameDiagnostics","false","Bool","",false,{}},
    Field{"Debug","LogPerformanceMetrics","Debug","LogPerformanceMetrics","false","Bool","",false,{}},
    Field{"Debug","PerformanceLogIntervalSeconds","Debug","PerformanceLogIntervalSeconds","10","Number","",false,{}},
    Field{"Debug","LogMenuMetrics","Debug","LogMenuMetrics","false","Bool","",false,{}},
    Field{"Menu","WindowX","Menu","WindowX","40","Number","",false,{}},
    Field{"Menu","WindowY","Menu","WindowY","40","Number","",false,{}},
    Field{"Menu","WindowWidth","Menu","WindowWidth","640","Number","",false,{}},
    Field{"Menu","WindowHeight","Menu","WindowHeight","720","Number","",false,{}},
    Field{"Menu","LeftColumnFraction","Menu","LeftColumnFraction","0.5","Number","",false,{}},
};
}
