include_guard(GLOBAL)
get_filename_component(TRP_AMD_NR_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
add_library(TRPAmdNrCore STATIC "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/WeightArchive.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/NumericFormats.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/ModelGeometry.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/ModelIdentity.cpp")
target_link_libraries(TRPAmdNrCore PUBLIC bcrypt)
target_compile_definitions(TRPAmdNrCore PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN)
add_executable(TRPAmdNrInspect "${TRP_AMD_NR_ROOT}/tools/AmdNrInspect.cpp")
target_link_libraries(TRPAmdNrInspect PRIVATE TRPAmdNrCore)
target_compile_features(TRPAmdNrCore PUBLIC cxx_std_23)
target_include_directories(TRPAmdNrCore PUBLIC "${TRP_AMD_NR_ROOT}/src")
if(MSVC)
    target_compile_options(TRPAmdNrCore PRIVATE /W4 /permissive-)
endif()
