include_guard(GLOBAL)
get_filename_component(TRP_AMD_NR_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
add_library(TRPAmdNrCore STATIC "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/WeightArchive.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/NumericFormats.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/ModelGeometry.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/ModelIdentity.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/C512Projection.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/C512ProjectionArchive.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/C512Tensor.cpp")
target_sources(TRPAmdNrCore PRIVATE "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/C512Reduction.cpp")
target_link_libraries(TRPAmdNrCore PUBLIC bcrypt)
target_compile_definitions(TRPAmdNrCore PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN)
add_executable(TRPAmdNrInspect "${TRP_AMD_NR_ROOT}/tools/AmdNrInspect.cpp")
target_link_libraries(TRPAmdNrInspect PRIVATE TRPAmdNrCore)
add_executable(TRPCompileAmdNrShaders "${TRP_AMD_NR_ROOT}/tools/CompileAmdNrShaders.cpp")
target_compile_features(TRPCompileAmdNrShaders PRIVATE cxx_std_23)
target_compile_definitions(TRPCompileAmdNrShaders PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_link_libraries(TRPCompileAmdNrShaders PRIVATE d3dcompiler)
set(TRP_AMD_NR_SHADER_HEADER "${CMAKE_CURRENT_BINARY_DIR}/amd-nr-generated/FormatCodecBytecode.h")
add_custom_command(OUTPUT "${TRP_AMD_NR_SHADER_HEADER}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/amd-nr-generated"
    COMMAND TRPCompileAmdNrShaders "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/Shaders/FormatCodec.hlsl" "${TRP_AMD_NR_SHADER_HEADER}"
    DEPENDS TRPCompileAmdNrShaders "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/Shaders/FormatCodec.hlsl" VERBATIM)
add_library(TRPAmdNrProbe STATIC "${TRP_AMD_NR_ROOT}/src/NeuralRendering/Amd/FormatProbe.cpp" "${TRP_AMD_NR_SHADER_HEADER}")
target_include_directories(TRPAmdNrProbe PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/amd-nr-generated")
target_link_libraries(TRPAmdNrProbe PUBLIC TRPAmdNrCore d3d12 dxgi)
add_executable(TRPAmdNrFormatProbe "${TRP_AMD_NR_ROOT}/tools/AmdNrFormatProbe.cpp")
target_link_libraries(TRPAmdNrFormatProbe PRIVATE TRPAmdNrProbe)
if(MSVC)
    target_compile_options(TRPAmdNrProbe PRIVATE /W4 /permissive-)
endif()
target_compile_features(TRPAmdNrCore PUBLIC cxx_std_23)
target_include_directories(TRPAmdNrCore PUBLIC "${TRP_AMD_NR_ROOT}/src")
if(MSVC)
    target_compile_options(TRPAmdNrCore PRIVATE /W4 /permissive-)
endif()
