# Active NVIDIA plugin sources.
set(ARP_BASELINE_SOURCES
    compatibility/ImGuiCompat/ImGuiIntegration.cpp
    compatibility/ImGuiCompat/ImGuiIntegration.h
    compatibility/ImGuiCompat/CursorMapping.h
    compatibility/ImGuiCompat/ModexMenuScope.cpp
    compatibility/ImGuiCompat/ModexMenuScope.h
    compatibility/Shared/FileHash.h
    compatibility/Shared/ModuleInfo.h
    include/PCH.h
    include/SolFGLateOverlayAPI.h
    include/SolFGStartupOverlayAPI.h
    include/SolFGTextureProviderAPI.h
    src/D3D11ContextSlots.h
    src/DLSSBackend.cpp
    src/GameHookValidation.cpp
    src/GameHookValidation.h
    src/HookSafety.h
    src/HookInstallation.h
    src/RuntimePathSettings.h
    src/CommunityShaderIntegration.cpp
    src/CommunityShaderIntegration.h
    src/CommunityShaderUIBoundary.h
    src/FrameGen/D3D11EntryObservers.h
    src/DLSSBackend.h
    src/RCASParameters.h
    src/DLSSFeatureParameters.h
    src/DLSSPreset.h
    src/NativeInput.h
    src/NativeUIBridge.h
    src/NativeInputThunks.h
    src/NvidiaUpscalerConfiguration.h
    src/FrameGen/SourceUpscalerConfiguration.cpp
    src/FrameGen/PresentationTargets.h
    src/FrameGen/GameFacingTargets.h
    src/FrameGen/NativeUIComposition.h
    src/FrameGen/NativeUIBlend.h
    src/FrameGen/NativeUIBlend.cpp
    src/FrameGen/NativeUIPass.h
    src/FrameGen/SourceFrameCoordinator.h
    src/FrameGen/SourceNvidiaFrameEvaluator.h
    src/FrameGen/SourceNvidiaFramePreparation.h
    src/FrameGen/SourceCameraSelection.h
    src/FrameGen/CameraMeasurements.cpp
    src/FrameGen/GameCameraMeasurements.cpp
    src/FrameGen/SourceFsrEvaluation.cpp
    src/FrameGen/D3D11FrameCopy.h
    src/FrameGen/D3D11ContextIsolation.h
    src/FrameGen/FinalFrameCapture.h
    src/FrameGen/CommunityShaderFrame.h
    src/FrameGen/CommunityShaderAdapter.h
    src/FrameGen/CommunityShaderAdapter.cpp
    src/FrameGen/SourceNvidiaEvaluation.cpp
    src/FrameGen/LoadingArtwork.cpp
    src/FrameGen/LoadingArtwork.h
    src/FrameGen/LoadingArtworkPolicy.h
    src/FrameGen/LoadingScreenState.h
    src/FrameGen/LoadingScreenUpscaler.h
    src/FrameGen/LoadingFadeIn.h
    src/FrameGen/PresentationFade.cpp
    src/FrameGen/PresentationFade.h
    src/FrameGen/SourceFrameGeneration.h
    src/FrameGen/SourceFrameGeneration.cpp
    src/FrameGen/InventoryPreviewDraw.h
    src/FrameGen/InventoryPreviewDraw.cpp
    src/FrameGen/NvidiaHost.h
    src/FrameGen/OrdinaryPresentation.cpp
    src/FrameGen/NvidiaHost.cpp
    src/FrameGen/NvidiaHostStartup.cpp
    src/FrameGen/NvidiaHostLifecycle.cpp
    src/FrameGen/SourceHostLifecycle.h
    src/FrameGen/SourceHostBoundary.h
    src/FrameGen/SourceGenerationPolicy.h
    src/FrameGen/GameSwapChain.h
    src/FrameGen/GameSwapChain.cpp
    src/FrameGen/StartupUIClipping.h
    src/FrameGen/StartupOverlayPass.h
    src/FrameGen/NativeUIFrame.h
    src/FrameGen/NativeUIAttachments.h
    src/FrameGen/NativeUICopyRoute.h
    src/FrameGen/NativeUIContexts.h
    src/FrameGen/SourceNativeUI.cpp
    src/FrameGen/NativeUIComposition.cpp
    src/DRS.cpp
    src/DRS.h
    src/MenuRenderState.h
    src/RenderPipeline.cpp
    src/WeatherAppearance.h
    src/WeatherEditorID.h
    src/WeatherAppearanceController.h
    src/WeatherAppearanceINI.h
    src/WeatherAppearanceRuntime.h
    src/WeatherAppearanceRuntime.cpp
    src/WeatherAppearanceSetup.h
    src/WeatherAppearanceFiles.h
    src/OverlayPresetsPanel.cpp
    src/RenderPipeline.h
    src/ReShadeIntegration.h
    src/ReShadeSwapChain.h
    src/ScreenshotFile.cpp
    src/ScreenshotFile.h
    src/ScreenshotWorker.h
    src/IniLayout.h
    src/SettingsFile.h
    src/PluginPaths.h
    src/SkyrimRuntime.h
    src/UpscaleType.h
    src/FrameGen/NeuralRenderingFeatureSession.h
    src/FrameGen/NeuralRenderingCreationContext.h
    src/FrameGen/NeuralRenderingModulePathHook.h
    src/FrameGen/NeuralRenderingReconstruction.h
    src/FrameGen/NeuralRenderingRuntimeContract.h
    src/FrameGen/NeuralRenderingRuntimeIdentity.h
    src/FrameGen/NeuralRenderingPassSettings.h
    src/FrameGen/SourceDLSSGNeuralSecondPass.inl
    src/FrameGen/NeuralRenderingTuning.h
    src/FrameGen/SourceDLSSGMFGPatch.h
    src/FrameGen/SourceDLSSGBackend.cpp
    src/FrameGen/SourceDLSSGBackend.h
    src/FrameGen/SourceDLSSGCamera.cpp
    src/FrameGen/SourceDLSSGCamera.h
    src/FrameGen/SourceDLSSGCameraMath.cpp
    src/FrameGen/SourceDLSSGGeneration.h
    src/FrameGen/SourceDLSSGHDR.cpp
    src/FrameGen/SourceDLSSGHDR.h
    src/FrameGen/HDRColorimetry.h
    src/FrameGen/HDROutput.h
    src/FrameGen/SourceDLSSGHDROutput.cpp
    src/FrameGen/SourceDLSSGHDROutput.h
    src/Graphics/D3D11D3D12Interop.cpp
    src/FrameGen/SourceDLSSGInterop.cpp
    src/FrameGen/SourceDLSSGInterop.h
    src/FrameGen/SourceDLSSGMFG.h
    src/FrameGen/SourceDLSSGMFGContract.h
    src/FrameGen/SourceDLSSGNeuralRendering.h
    src/FrameGen/SourceDLSSGNeuralState.h
    src/FrameGen/SourceDLSSGNeuralResolve.h
    src/FrameGen/SourceDLSSGNeuralResolveShader.h
    src/FrameGen/SourceDLSSGNeuralTelemetry.h
    src/FrameGen/SourceDLSSGOutputBatches.h
    src/FrameGen/SourceDLSSGPresentationFeedback.h
    src/FrameGen/SourceDLSSGReflexTelemetry.h
    src/FrameGen/SourceDLSSGRuntimeDiagnostics.h
    src/FrameGen/SourceDLSSGSession.cpp
    src/FrameGen/SourceDLSSGSession.h
    src/FrameGen/SourceDLSSGSettings.h
    src/FrameGen/SourceDLSSGSwapChain.cpp
    src/FrameGen/SourceDLSSGSwapChain.h
    src/FrameTelemetry.h
    src/FrameTrace.cpp
    src/FrameTrace.h
    src/NvidiaBaselinePolicy.h
    src/OverlayNumericInput.h
    src/OverlayHotkeys.cpp
    src/OverlayHotkeys.h
    src/OverlayGameInput.cpp
    src/OverlayGameInput.h
    src/OverlayUI.cpp
    src/OverlayRazkolbasPanel.cpp
    src/OverlayFrameView.cpp
    src/OverlayFrameView.h
    src/OverlayPipeline.cpp
    src/OverlayPipeline.h
    src/OverlayLayout.cpp
    src/OverlayLayout.h
    src/OverlayImagePanel.cpp
    src/OverlayAdvancedPanel.cpp
    src/OverlayUIStyle.cpp
    src/OverlayUIStyle.h
    src/OverlayPresetDecor.h
    src/OverlaySettingRows.h
    src/OverlayFrameGenerationPanel.cpp
    src/OverlayPerformancePanel.cpp
    src/OverlayUI.h
    src/OverlayRenderTarget.h
    src/RendererSettings.h
    src/RendererSettingsController.h
    src/RendererSettingsController.cpp
    src/PerformanceTuning.cpp
    src/PerformanceTuning.h
    src/RE/BSGraphics.h
    src/TextureProviderBridge.cpp
    src/TextureProviderBridge.h
    src/UpscalerHooks.cpp
    src/UpscalerHooks.h
    src/UpscalerDeviceHooks.cpp
    src/UpscalerDeviceHooks.h
    src/UpscalerSamplerHooks.cpp
    src/UpscalerSamplerHooks.h
    src/VideoMemoryTelemetry.cpp
    src/VideoMemoryTelemetry.h
    src/XSEPlugin.cpp
)

# Neural Rendering is available independently of MFG compatibility.
set(ARP_NEURAL_SOURCES
    src/NeuralCombatMode.cpp
    src/NeuralCombatMode.h
    src/NeuralCombatPolicy.h
    src/FrameGen/NeuralRenderingFeatureSession.cpp
    src/FrameGen/NeuralRenderingModulePathHook.cpp
    src/FrameGen/NeuralRenderingRuntimeIdentity.cpp
    src/FrameGen/SourceDLSSGNeuralRendering.cpp
    src/FrameGen/SourceDLSSGNeuralStage.cpp
    src/FrameGen/SourceDLSSGNeuralResolve.cpp
    src/OverlayNeuralPanel.cpp
)
