option(TRP_ENABLE_FSR "Build optional FidelityFX SR integration" OFF)
set(TRP_FSR_SDK_DIR "${PROJECT_SOURCE_DIR}/.dependencies/FidelityFX-SDK-v2.3.0" CACHE PATH "Verified pinned FidelityFX headers/runtime root")
if(TRP_ENABLE_FSR)
    set(TRP_FSR_API_INCLUDE "${TRP_FSR_SDK_DIR}/Kits/FidelityFX/api/include")
    set(TRP_FSR_UPSCALE_INCLUDE "${TRP_FSR_SDK_DIR}/Kits/FidelityFX/upscalers/include")
    file(READ "${PROJECT_SOURCE_DIR}/tools/fsr/runtime-pin.json" pin)
    foreach(index RANGE 0 3)
        string(JSON headerPath GET "${pin}" headers ${index} path)
        string(JSON expectedHash GET "${pin}" headers ${index} sha256)
        set(header "${TRP_FSR_SDK_DIR}/${headerPath}")
        if(NOT EXISTS "${header}")
            message(FATAL_ERROR "Pinned FidelityFX header missing: ${header}. Run tools/fsr/Acquire-Runtime.ps1 or disable TRP_ENABLE_FSR.")
        endif()
        file(SHA256 "${header}" actualHash)
        if(NOT actualHash STREQUAL expectedHash)
            message(FATAL_ERROR "Pinned FidelityFX header SHA-256 differs: ${header}. Reacquire the pinned SDK.")
        endif()
    endforeach()
    add_library(TRPFsrRuntime STATIC src/Upscaling/FSRRuntime.cpp src/Upscaling/FSRParameters.cpp src/Upscaling/FSRUpscaler.cpp src/Upscaling/FSRHostResources.cpp src/Upscaling/FSRColorConversion.cpp src/Upscaling/FSRFrameAdapter.cpp)
    target_compile_features(TRPFsrRuntime PUBLIC cxx_std_23)
    target_compile_definitions(TRPFsrRuntime PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN TRP_ENABLE_FSR)
    target_include_directories(TRPFsrRuntime PUBLIC src "${TRP_FSR_API_INCLUDE}" "${TRP_FSR_UPSCALE_INCLUDE}")
    target_link_libraries(TheosRenderPipeline PRIVATE TRPFsrRuntime)
endif()

function(trp_add_fsr_tests)
    if(NOT TRP_ENABLE_FSR)
        return()
    endif()
    add_executable(TRPFsrRuntimeTests tests/FSRRuntimeTests.cpp)
    target_link_libraries(TRPFsrRuntimeTests PRIVATE TRPFsrRuntime)
    add_test(NAME FsrRuntime COMMAND TRPFsrRuntimeTests "${CMAKE_CURRENT_BINARY_DIR}/fsr-fixtures")
    add_executable(TRPFsrParametersTests tests/FSRParametersTests.cpp src/Graphics/D3D11D3D12Interop.cpp)
    target_link_libraries(TRPFsrParametersTests PRIVATE TRPFsrRuntime d3d11 d3d12 dxgi)
    add_test(NAME FsrParameters COMMAND TRPFsrParametersTests "${CMAKE_CURRENT_BINARY_DIR}/fsr-fixtures/good")
    add_subdirectory(tests/fsr-gpu)
    foreach(test IN ITEMS Startup Lifecycle History ColorContract FrameIntegration)
        add_executable(TRPFsr${test}Tests tests/FSR${test}Tests.cpp src/Graphics/D3D11D3D12Interop.cpp src/FrameGen/OrdinaryPresentation.cpp)
        target_link_libraries(TRPFsr${test}Tests PRIVATE TRPFsrRuntime TRPReShadeIntegration d3d11 d3d12 dxgi d3dcompiler)
        add_test(NAME Fsr${test} COMMAND TRPFsr${test}Tests "${CMAKE_CURRENT_BINARY_DIR}/fsr-fixtures/good")
    endforeach()
    foreach(index RANGE 0 5)
        if(index EQUAL 0)
            set(case good)
        else()
            set(case missing${index})
        endif()
        add_library(TRPFsrDouble${index} SHARED tests/fixtures/fsr/RuntimeDouble.cpp)
        target_compile_features(TRPFsrDouble${index} PRIVATE cxx_std_23)
        target_compile_definitions(TRPFsrDouble${index} PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN FSR_MISSING_EXPORT=${index})
        target_include_directories(TRPFsrDouble${index} PRIVATE "${TRP_FSR_API_INCLUDE}" "${TRP_FSR_UPSCALE_INCLUDE}")
        set(fixtureDir "${CMAKE_CURRENT_BINARY_DIR}/fsr-fixtures/${case}/FSR")
        set_target_properties(TRPFsrDouble${index} PROPERTIES OUTPUT_NAME amd_fidelityfx_loader_dx12 RUNTIME_OUTPUT_DIRECTORY_RELEASE "${fixtureDir}" ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${fixtureDir}")
        add_custom_command(TARGET TRPFsrDouble${index} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "$<TARGET_FILE:TRPFsrDouble${index}>" "${fixtureDir}/amd_fidelityfx_upscaler_dx12.dll")
        add_dependencies(TRPFsrRuntimeTests TRPFsrDouble${index})
        add_dependencies(TRPFsrParametersTests TRPFsrDouble${index})
        add_dependencies(TRPFsrStartupTests TRPFsrDouble${index})
        add_dependencies(TRPFsrLifecycleTests TRPFsrDouble${index})
        add_dependencies(TRPFsrHistoryTests TRPFsrDouble${index})
        add_dependencies(TRPFsrColorContractTests TRPFsrDouble${index})
        add_dependencies(TRPFsrFrameIntegrationTests TRPFsrDouble${index})
    endforeach()
endfunction()
