option(TRP_ENABLE_XESS_FG "Build optional public Intel FG/XeLL presentation" OFF)
if(TRP_ENABLE_XESS_FG)
    file(READ "${PROJECT_SOURCE_DIR}/tools/xess/sdk-pin.json" xessFgPin)
    foreach(index RANGE 0 3)
        string(JSON headerPath GET "${xessFgPin}" generationFiles ${index} path)
        string(JSON expectedHash GET "${xessFgPin}" generationFiles ${index} sha256)
        set(header "${TRP_XESS_SDK_DIR}/${headerPath}")
        if(NOT EXISTS "${header}")
            message(FATAL_ERROR "Pinned Intel FG header missing: ${header}. Run tools/xess/Acquire-Sdk.ps1 -FrameGeneration.")
        endif()
        file(SHA256 "${header}" actualHash)
        if(NOT actualHash STREQUAL expectedHash)
            message(FATAL_ERROR "Pinned Intel FG header differs: ${header}")
        endif()
    endforeach()
    add_library(TRPXessGeneration STATIC src/FrameGen/XessGenerationRuntime.cpp
        src/FrameGen/XessGenerationFrameAdapter.cpp src/FrameGen/XessGenerationPolicy.cpp src/FrameGen/XellSession.cpp
        src/FrameGen/XessGenerationTransport.cpp src/FrameGen/XessGenerationPresentation.cpp src/FrameGen/XessGenerationEngineTiming.cpp src/FrameGen/XessGenerationHost.cpp src/Graphics/D3D11D3D12Interop.cpp
        src/Upscaling/FSRColorConversion.cpp src/Upscaling/FSRPresentationColor.cpp)
    target_compile_features(TRPXessGeneration PUBLIC cxx_std_23)
    target_compile_definitions(TRPXessGeneration PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN TRP_ENABLE_XESS_FG)
    target_include_directories(TRPXessGeneration PUBLIC src "${TRP_XESS_SDK_DIR}/inc")
    target_link_libraries(TRPXessGeneration PUBLIC d3d11 d3d12 dxgi d3dcompiler)
    target_link_libraries(RaZkolbaS PRIVATE TRPXessGeneration)
endif()
function(trp_add_xess_fg_tests)
    if(NOT TRP_ENABLE_XESS_FG)
        return()
    endif()
    foreach(kind generation latency)
        add_library(TRPXessFgDouble_${kind} SHARED tests/fixtures/xess-fg/RuntimeDouble.cpp)
        target_include_directories(TRPXessFgDouble_${kind} PRIVATE "${TRP_XESS_SDK_DIR}/inc")
        if(kind STREQUAL "latency")
            target_compile_definitions(TRPXessFgDouble_${kind} PRIVATE FIXTURE_LATENCY XELL_EXPORT_API)
            set(name libxell)
        else()
            target_compile_definitions(TRPXessFgDouble_${kind} PRIVATE XEFG_SWAPCHAIN_EXPORT_API)
            set(name libxess_fg)
        endif()
        set_target_properties(TRPXessFgDouble_${kind} PROPERTIES OUTPUT_NAME ${name}
            ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS"
            ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS"
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS")
    endforeach()
    add_executable(TRPXessFgRuntimeTests tests/XessFgRuntimeTests.cpp)
    target_link_libraries(TRPXessFgRuntimeTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgRuntimeTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgRuntime COMMAND TRPXessFgRuntimeTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures")
    add_executable(TRPXessFgRuntimeProbe tests/xess-fg/XessFgRuntimeProbe.cpp)
    target_link_libraries(TRPXessFgRuntimeProbe PRIVATE TRPXessGeneration)
    add_test(NAME XessFgRuntimeGpu COMMAND TRPXessFgRuntimeProbe --plugin-directory "${TRP_XESS_SDK_DIR}/SKSE/Plugins")
    set_tests_properties(XessFgRuntimeGpu PROPERTIES LABELS GPU TIMEOUT 60)
    foreach(kind FrameAdapter Policy)
        add_executable(TRPXessFg${kind}Tests tests/XessFg${kind}Tests.cpp)
        target_link_libraries(TRPXessFg${kind}Tests PRIVATE TRPXessGeneration)
        add_test(NAME XessFg${kind} COMMAND TRPXessFg${kind}Tests)
    endforeach()
    add_executable(TRPXessFgLatencyTests tests/XessFgLatencyTests.cpp)
    target_link_libraries(TRPXessFgLatencyTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgLatencyTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgLatency COMMAND TRPXessFgLatencyTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good")
    add_executable(TRPXessFgTransportTests tests/XessFgTransportTests.cpp)
    target_include_directories(TRPXessFgTransportTests PRIVATE tests)
    target_link_libraries(TRPXessFgTransportTests PRIVATE TRPXessGeneration)
    add_test(NAME XessFgTransport COMMAND TRPXessFgTransportTests)
    set_tests_properties(XessFgTransport PROPERTIES LABELS GPU RUN_SERIAL TRUE TIMEOUT 60)
    add_executable(TRPXessFgPresentationTests tests/XessFgPresentationTests.cpp)
    target_include_directories(TRPXessFgPresentationTests PRIVATE tests)
    target_link_libraries(TRPXessFgPresentationTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgPresentationTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgPresentation COMMAND TRPXessFgPresentationTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good")
    set_tests_properties(XessFgPresentation PROPERTIES LABELS GPU RUN_SERIAL TRUE TIMEOUT 60)
    add_executable(TRPXessFgPresentationGpuTests tests/xess-fg/XessFgPresentationGpuTests.cpp)
    target_include_directories(TRPXessFgPresentationGpuTests PRIVATE tests)
    target_link_libraries(TRPXessFgPresentationGpuTests PRIVATE TRPXessGeneration)
    add_test(NAME XessFgPresentationGpu COMMAND TRPXessFgPresentationGpuTests --plugin-directory "${TRP_XESS_SDK_DIR}/SKSE/Plugins")
    set_tests_properties(XessFgPresentationGpu PROPERTIES LABELS GPU RUN_SERIAL TRUE TIMEOUT 60)
    add_executable(TRPXessFgEngineTimingTests tests/XessFgEngineTimingTests.cpp)
    target_link_libraries(TRPXessFgEngineTimingTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgEngineTimingTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgEngineTiming COMMAND TRPXessFgEngineTimingTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good")
    foreach(kind Settings Routing)
        add_executable(TRPXessFg${kind}Tests tests/XessFg${kind}Tests.cpp)
        target_include_directories(TRPXessFg${kind}Tests PRIVATE include "${TRP_SIMPLEINI_INCLUDE_DIR}" "${TRP_STREAMLINE_INCLUDE_DIR}")
        target_link_libraries(TRPXessFg${kind}Tests PRIVATE TRPXessGeneration)
        if(TRP_ENABLE_XESS)
            target_compile_definitions(TRPXessFg${kind}Tests PRIVATE TRP_ENABLE_XESS)
        endif()
        add_test(NAME XessFg${kind} COMMAND TRPXessFg${kind}Tests)
    endforeach()
    add_executable(TRPXessFgHostTests tests/XessFgHostTests.cpp)
    target_include_directories(TRPXessFgHostTests PRIVATE tests)
    target_link_libraries(TRPXessFgHostTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgHostTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgHost COMMAND TRPXessFgHostTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good")
    set_tests_properties(XessFgHost PROPERTIES LABELS GPU RUN_SERIAL TRUE TIMEOUT 60 SKIP_RETURN_CODE 77)
    add_executable(TRPXessFgNeuralRouteTests tests/XessFgNeuralRouteTests.cpp)
    target_include_directories(TRPXessFgNeuralRouteTests PRIVATE tests)
    target_link_libraries(TRPXessFgNeuralRouteTests PRIVATE TRPXessGeneration)
    add_test(NAME XessFgNeuralRoute COMMAND TRPXessFgNeuralRouteTests)
    add_executable(TRPXessFgTelemetryTests tests/XessFgTelemetryTests.cpp)
    target_link_libraries(TRPXessFgTelemetryTests PRIVATE TRPXessGeneration)
    add_test(NAME XessFgTelemetry COMMAND TRPXessFgTelemetryTests)
    add_executable(TRPXessFgLifecycleTests tests/XessFgLifecycleTests.cpp)
    target_include_directories(TRPXessFgLifecycleTests PRIVATE tests)
    target_link_libraries(TRPXessFgLifecycleTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgLifecycleTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgLifecycle COMMAND TRPXessFgLifecycleTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good")
    set_tests_properties(XessFgLifecycle PROPERTIES LABELS GPU RUN_SERIAL TRUE TIMEOUT 60 SKIP_RETURN_CODE 77)
    add_test(NAME XessFgPackage COMMAND pwsh.exe -NoProfile -File "${PROJECT_SOURCE_DIR}/tests/XessFgPackageTests.ps1" -SdkDirectory "${TRP_XESS_SDK_DIR}" -ScratchRoot "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-package-fixtures")
    set_tests_properties(XessFgPackage PROPERTIES TIMEOUT 60)
endfunction()
function(trp_add_xess_fg_source_tests)
    if(NOT TRP_ENABLE_XESS_FG OR NOT TARGET TRPXessRuntime OR NOT TARGET TRPFsrRuntime OR NOT TARGET TRPNeuralRuntime)
        return()
    endif()
    set(TRP_XESS_FG_FSR_PLUGIN_DIRECTORY "" CACHE PATH "Pinned FSR 3.1.5 plugin fixture for Intel FG source probe")
    if(NOT TRP_XESS_FG_FSR_PLUGIN_DIRECTORY OR NOT TRP_NR_TEST_RUNTIME_ROOT OR NOT TRP_NR_DRIVER_CORE)
        return()
    endif()
    add_executable(TRPXessFgSourceGpuTests tests/xess-fg/XessFgSourceGpuTests.cpp)
    target_include_directories(TRPXessFgSourceGpuTests PRIVATE tests)
    target_link_libraries(TRPXessFgSourceGpuTests PRIVATE TRPXessGeneration TRPXessRuntime TRPFsrRuntime TRPNeuralRuntime user32 bcrypt)
    add_test(NAME XessFgSourceGpu COMMAND TRPXessFgSourceGpuTests "${TRP_XESS_SDK_DIR}/SKSE/Plugins" "${TRP_NR_TEST_RUNTIME_ROOT}" "${TRP_NR_DRIVER_CORE}" "${TRP_XESS_FG_FSR_PLUGIN_DIRECTORY}")
    set_tests_properties(XessFgSourceGpu PROPERTIES LABELS GPU RUN_SERIAL TRUE TIMEOUT 240 SKIP_RETURN_CODE 77)
endfunction()
