option(TRP_ENABLE_XESS_FG "Build optional public Intel FG/XeLL presentation" OFF)
if(TRP_ENABLE_XESS_FG)
    file(READ "${PROJECT_SOURCE_DIR}/tools/xess/sdk-pin.json" xessFgPin)
    foreach(index RANGE 0 3)
        string(JSON headerPath GET "${xessFgPin}" generationFiles ${index} path)
        string(JSON expectedHash GET "${xessFgPin}" generationFiles ${index} sha256)
        set(header "${TRP_XESS_SDK_DIR}/${headerPath}")
        if(NOT EXISTS "${header}")
            message(FATAL_ERROR "Pinned Intel FG header missing: ${header}. Run tools/xess/Acquire-Sdk.ps1 -FrameGeneration.")
        endif()
        file(SHA256 "${header}" actualHash)
        if(NOT actualHash STREQUAL expectedHash)
            message(FATAL_ERROR "Pinned Intel FG header differs: ${header}")
        endif()
    endforeach()
    add_library(TRPXessGeneration STATIC src/FrameGen/XessGenerationRuntime.cpp
        src/FrameGen/XessGenerationFrameAdapter.cpp src/FrameGen/XessGenerationPolicy.cpp)
    target_compile_features(TRPXessGeneration PUBLIC cxx_std_23)
    target_compile_definitions(TRPXessGeneration PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN TRP_ENABLE_XESS_FG)
    target_include_directories(TRPXessGeneration PUBLIC src "${TRP_XESS_SDK_DIR}/inc")
    target_link_libraries(TRPXessGeneration PUBLIC d3d11 d3d12 dxgi)
    target_link_libraries(RaZkolbaS PRIVATE TRPXessGeneration)
endif()
function(trp_add_xess_fg_tests)
    if(NOT TRP_ENABLE_XESS_FG)
        return()
    endif()
    foreach(kind generation latency)
        add_library(TRPXessFgDouble_${kind} SHARED tests/fixtures/xess-fg/RuntimeDouble.cpp)
        target_include_directories(TRPXessFgDouble_${kind} PRIVATE "${TRP_XESS_SDK_DIR}/inc")
        if(kind STREQUAL "latency")
            target_compile_definitions(TRPXessFgDouble_${kind} PRIVATE FIXTURE_LATENCY XELL_EXPORT_API)
            set(name libxell)
        else()
            target_compile_definitions(TRPXessFgDouble_${kind} PRIVATE XEFG_SWAPCHAIN_EXPORT_API)
            set(name libxess_fg)
        endif()
        set_target_properties(TRPXessFgDouble_${kind} PROPERTIES OUTPUT_NAME ${name}
            ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS"
            ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS"
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures/good/RaZkolbaS/XeSS")
    endforeach()
    add_executable(TRPXessFgRuntimeTests tests/XessFgRuntimeTests.cpp)
    target_link_libraries(TRPXessFgRuntimeTests PRIVATE TRPXessGeneration)
    add_dependencies(TRPXessFgRuntimeTests TRPXessFgDouble_generation TRPXessFgDouble_latency)
    add_test(NAME XessFgRuntime COMMAND TRPXessFgRuntimeTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fg-fixtures")
    add_executable(TRPXessFgRuntimeProbe tests/xess-fg/XessFgRuntimeProbe.cpp)
    target_link_libraries(TRPXessFgRuntimeProbe PRIVATE TRPXessGeneration)
    add_test(NAME XessFgRuntimeGpu COMMAND TRPXessFgRuntimeProbe --plugin-directory "${TRP_XESS_SDK_DIR}/SKSE/Plugins")
    set_tests_properties(XessFgRuntimeGpu PROPERTIES LABELS GPU TIMEOUT 60)
    foreach(kind FrameAdapter Policy)
        add_executable(TRPXessFg${kind}Tests tests/XessFg${kind}Tests.cpp)
        target_link_libraries(TRPXessFg${kind}Tests PRIVATE TRPXessGeneration)
        add_test(NAME XessFg${kind} COMMAND TRPXessFg${kind}Tests)
    endforeach()
endfunction()
