option(TRP_ENABLE_XESS "Build optional XeSS D3D12 SR integration" OFF)
set(TRP_XESS_SDK_DIR "${PROJECT_SOURCE_DIR}/out/research/xess-sdk-3.0.2" CACHE PATH "Verified minimal XeSS SDK root")
if(TRP_ENABLE_XESS)
    file(READ "${PROJECT_SOURCE_DIR}/tools/xess/sdk-pin.json" xessPin)
    foreach(index RANGE 0 1)
        string(JSON headerPath GET "${xessPin}" files ${index} path)
        string(JSON expectedHash GET "${xessPin}" files ${index} sha256)
        set(header "${TRP_XESS_SDK_DIR}/${headerPath}")
        if(NOT EXISTS "${header}")
            message(FATAL_ERROR "Pinned XeSS header missing: ${header}. Run tools/xess/Acquire-Sdk.ps1.")
        endif()
        file(SHA256 "${header}" actualHash)
        if(NOT actualHash STREQUAL expectedHash)
            message(FATAL_ERROR "Pinned XeSS header differs: ${header}")
        endif()
    endforeach()
    add_library(TRPXessRuntime STATIC src/Upscaling/XessRuntime.cpp src/Upscaling/XessFrameAdapter.cpp src/Upscaling/XessUpscaler.cpp src/Upscaling/XessHostResources.cpp)
    target_compile_features(TRPXessRuntime PUBLIC cxx_std_23)
    target_compile_definitions(TRPXessRuntime PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN)
    target_include_directories(TRPXessRuntime PUBLIC src "${TRP_XESS_SDK_DIR}/inc")
    target_link_libraries(TRPXessRuntime PUBLIC TRPSdrColorConversion d3d11 d3d12 dxgi)
    target_compile_definitions(TRPXessRuntime PUBLIC TRP_ENABLE_XESS)
    target_link_libraries(RaZkolbaS PRIVATE TRPXessRuntime)
    add_executable(TRPXessRuntimeProbe tests/xess-gpu/XessRuntimeProbe.cpp)
    target_link_libraries(TRPXessRuntimeProbe PRIVATE TRPXessRuntime d3d11 d3d12 dxgi)
endif()
function(trp_add_xess_tests)
    if(NOT TRP_ENABLE_XESS)
        return()
    endif()
    add_executable(TRPXessRuntimeTests tests/XessRuntimeTests.cpp)
    target_link_libraries(TRPXessRuntimeTests PRIVATE TRPXessRuntime)
    foreach(case good missing)
        add_library(TRPXessDouble_${case} SHARED tests/fixtures/xess/RuntimeDouble.cpp)
        target_include_directories(TRPXessDouble_${case} PRIVATE "${TRP_XESS_SDK_DIR}/inc")
        target_compile_definitions(TRPXessDouble_${case} PRIVATE XESS_SHARED_LIB XESS_EXPORT_API)
        if(case STREQUAL missing)
            target_compile_definitions(TRPXessDouble_${case} PRIVATE XESS_MISSING_EXPORT)
        endif()
        set_target_properties(TRPXessDouble_${case} PROPERTIES OUTPUT_NAME libxess
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures/${case}/RaZkolbaS/XeSS"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures/${case}/RaZkolbaS/XeSS")
        add_dependencies(TRPXessRuntimeTests TRPXessDouble_${case})
    endforeach()
    add_test(NAME XessRuntime COMMAND TRPXessRuntimeTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures")
    add_executable(TRPXessFrameAdapterTests tests/XessFrameAdapterTests.cpp)
    target_link_libraries(TRPXessFrameAdapterTests PRIVATE TRPXessRuntime)
    add_test(NAME XessFrameAdapter COMMAND TRPXessFrameAdapterTests)
    add_executable(TRPXessNeuralRouteTests tests/XessNeuralRouteTests.cpp)
    target_include_directories(TRPXessNeuralRouteTests PRIVATE include "${TRP_SIMPLEINI_INCLUDE_DIR}" "${TRP_STREAMLINE_INCLUDE_DIR}")
    target_link_libraries(TRPXessNeuralRouteTests PRIVATE TRPXessRuntime)
    add_test(NAME XessNeuralRoute COMMAND TRPXessNeuralRouteTests)
    foreach(kind Settings Startup)
        add_executable(TRPXess${kind}Tests tests/Xess${kind}Tests.cpp)
        target_include_directories(TRPXess${kind}Tests PRIVATE "${TRP_SIMPLEINI_INCLUDE_DIR}")
        target_link_libraries(TRPXess${kind}Tests PRIVATE TRPXessRuntime)
        add_test(NAME Xess${kind} COMMAND TRPXess${kind}Tests)
    endforeach()
    add_executable(TRPXessLifecycleTests tests/XessLifecycleTests.cpp src/Graphics/D3D11D3D12Interop.cpp)
    target_link_libraries(TRPXessLifecycleTests PRIVATE TRPXessRuntime d3d11 d3d12 dxgi)
    add_dependencies(TRPXessLifecycleTests TRPXessDouble_good)
    add_test(NAME XessLifecycle COMMAND TRPXessLifecycleTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures/good")
    add_executable(TRPXessTemporalGpuTests tests/xess-gpu/XessTemporalGpuTests.cpp src/Graphics/D3D11D3D12Interop.cpp)
    target_include_directories(TRPXessTemporalGpuTests PRIVATE tests)
    target_link_libraries(TRPXessTemporalGpuTests PRIVATE TRPXessRuntime d3d11 d3d12 dxgi d3dcompiler)
    add_dependencies(TRPXessTemporalGpuTests TRPXessDouble_good)
    add_test(NAME XessTemporalGpu COMMAND TRPXessTemporalGpuTests "${TRP_XESS_SDK_DIR}/SKSE/Plugins" "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures/good")
    set_tests_properties(XessTemporalGpu PROPERTIES LABELS GPU TIMEOUT 120)
    add_test(NAME XessRuntimeGpu COMMAND TRPXessRuntimeProbe --plugin-directory "${TRP_XESS_SDK_DIR}/SKSE/Plugins")
    set_tests_properties(XessRuntimeGpu PROPERTIES LABELS GPU TIMEOUT 60)
endfunction()
