option(TRP_ENABLE_XESS "Build optional XeSS D3D12 SR integration" OFF)
set(TRP_XESS_SDK_DIR "${PROJECT_SOURCE_DIR}/out/research/xess-sdk-3.0.2" CACHE PATH "Verified minimal XeSS SDK root")
if(TRP_ENABLE_XESS)
    file(READ "${PROJECT_SOURCE_DIR}/tools/xess/sdk-pin.json" xessPin)
    foreach(index RANGE 0 1)
        string(JSON headerPath GET "${xessPin}" files ${index} path)
        string(JSON expectedHash GET "${xessPin}" files ${index} sha256)
        set(header "${TRP_XESS_SDK_DIR}/${headerPath}")
        if(NOT EXISTS "${header}")
            message(FATAL_ERROR "Pinned XeSS header missing: ${header}. Run tools/xess/Acquire-Sdk.ps1.")
        endif()
        file(SHA256 "${header}" actualHash)
        if(NOT actualHash STREQUAL expectedHash)
            message(FATAL_ERROR "Pinned XeSS header differs: ${header}")
        endif()
    endforeach()
    add_library(TRPXessRuntime STATIC src/Upscaling/XessRuntime.cpp)
    target_compile_features(TRPXessRuntime PUBLIC cxx_std_23)
    target_compile_definitions(TRPXessRuntime PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN)
    target_include_directories(TRPXessRuntime PUBLIC src "${TRP_XESS_SDK_DIR}/inc")
    add_executable(TRPXessRuntimeProbe tests/xess-gpu/XessRuntimeProbe.cpp)
    target_link_libraries(TRPXessRuntimeProbe PRIVATE TRPXessRuntime d3d11 d3d12 dxgi)
endif()
function(trp_add_xess_tests)
    if(NOT TRP_ENABLE_XESS)
        return()
    endif()
    add_executable(TRPXessRuntimeTests tests/XessRuntimeTests.cpp)
    target_link_libraries(TRPXessRuntimeTests PRIVATE TRPXessRuntime)
    foreach(case good missing)
        add_library(TRPXessDouble_${case} SHARED tests/fixtures/xess/RuntimeDouble.cpp)
        target_include_directories(TRPXessDouble_${case} PRIVATE "${TRP_XESS_SDK_DIR}/inc")
        target_compile_definitions(TRPXessDouble_${case} PRIVATE XESS_SHARED_LIB XESS_EXPORT_API)
        if(case STREQUAL missing)
            target_compile_definitions(TRPXessDouble_${case} PRIVATE XESS_MISSING_EXPORT)
        endif()
        set_target_properties(TRPXessDouble_${case} PROPERTIES OUTPUT_NAME libxess
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures/${case}/RaZkolbaS/XeSS"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures/${case}/RaZkolbaS/XeSS")
        add_dependencies(TRPXessRuntimeTests TRPXessDouble_${case})
    endforeach()
    add_test(NAME XessRuntime COMMAND TRPXessRuntimeTests "${CMAKE_CURRENT_BINARY_DIR}/xess-fixtures")
    add_test(NAME XessRuntimeGpu COMMAND TRPXessRuntimeProbe --plugin-directory "${TRP_XESS_SDK_DIR}/SKSE/Plugins")
    set_tests_properties(XessRuntimeGpu PROPERTIES LABELS GPU TIMEOUT 60)
endfunction()
